### PR TITLE
docs: Fix missing links and links format in HIL README

### PR DESCRIPTION
**Pull request by playfulFence**
### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
There was no link for `ESP-Prog` provided.

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM!

**Review by SergioGasquez — CHANGES_REQUESTED** [review]
Ups! Good catch, thanks for fixing it. While reviewing, I also noticed that we also miss the link to probe-rs (https://github.com/esp-rs/esp-hal/blob/main/hil-test/README.md?plain=1#L19) mind adding it?

**Comment by playfulFence** [comment]
@SergioGasquez made a change. 

Also I've noticed that some of the links are in different formats, so I fixed that too, now all the links of each section are at the bottom of that section (like the rest of the READMEs in the project)

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
