### PR TITLE
Build examples in debug mode

### PR DESCRIPTION
**Pull request by bugadani**
- Don't spend time optimising examples in CI runs.
- We collect build artifacts after the fact, so building tests with multiple feature sets is a waste of time at this moment
- We're wasting a few seconds on rebuilding dependencies if features change. Some of it is unavoidable, but the rest might be saved by sorting examples by feature set.

### CODE REVIEW

**Comment by bugadani** [comment]
This gains us 70s on C2.

**Review by bjoernQ — APPROVED** [review]
Nice improvement

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for all your work improving CI

**Review by JurajSadel — APPROVED** [review]
Thanks!

**Pull request merged**
