### PR TITLE
Add `into_async` for ParlIO

### PR DESCRIPTION
**Pull request by bugadani**
Forgot to update parl_io in #2430. Still not sure what to do about TxOnly/RxOnly.

### CODE REVIEW

**Review by Dominaezzz — APPROVED** [review]
> Still not sure what to do about TxOnly/RxOnly.

At some point we should support converting each half of the DMA channel to and from blocking mode (on chips that an support it), which should solve this I think.

**Comment by bugadani** [comment]
We can do some runtime checks on chips that don't support it (unless the presence of the async handler poses a problem in blocking mode).

**Comment by Dominaezzz** [comment]
> unless the presence of the async handler poses a problem in blocking mode

It does, users could end up overriding the async handler, rendering the async driver broken.
Unless we implement some handler sharing logic like GPIO does but I don't like this direction.

**Comment by bugadani** [comment]
> It does, users could end up overriding the async handler, rendering the async driver broken.

That's what I mean by runtime checks, I'd just add a panic to prevent this.

**Comment by bugadani** [comment]
> Also, if it's gonna be a panic, might as well use the type system to prevent it. i.e. use cfg to remove the APIs on chips that don't support it.

"If it's gonna be a panic, don't use a panic" is a weird thing to say.

**Review by JurajSadel — APPROVED** [review]
Thanks!

**Pull request merged**
