### PR TITLE
MCPWM MVP implementation

### PR DESCRIPTION
**Pull request by dimpolo**
## Major things missing:

- [x] Need to resolve TODOs
- [x] Documentation
- [x] Test on ESP32 Hardware
- [x] Test on ESP32-S3 Hardware
- [ ] something else?

### Are we allowed to copy text passages from the reference manuals for documentation? What about pictures?
The MCPWM peripheral is quite complex with lots of moving parts so adding some graphics might help.

### What are people thinking about the API design? 
I chose an implementation without looking much at the existing `LEDC` code or the ESP IDF API.
There might be some disconnect here.

Things I tried to consider were (in no particular order):
* compile errors over runtime errors
* "zero-cost"-ness
* use of const-generics with the option of using [adt_const_params](https://github.com/rust-lang/rust/issues/95174) at some later point
* ability to add more features later without major architectural changes
* discoverability

I'd love to have some feedback here whether these goal were accomplished and if other considerations were missed.

### What's the pwm period of a Count-Up-Down Mode timer?
~~The [docs ](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf) mention:~~
~~> The PWM timer starts increasing from zero until the period value is reached. Then, the timer decreases back to zero. This pattern is then repeated. The PWM period is the result of (the value of the period field × 2 + 1)~~

~~Looking at the timing diagrams is seems to me that it would rather be `period field × 2`. Is that a mistake in the docs?~~

Doing some measurements confirmed that the docs indeed are wrong here the period is `period field × 2`

### CODE REVIEW

**Comment by bjoernQ** [comment]
> Are we allowed to copy text passages from the reference manuals for documentation? What about pictures?

I guess it's okay since the docs are Apache 2.0 license but I can ask internally.

Not looking into the LEDC driver is definitely a good thing since the API is not what we really want. It's just a port of the former attempt on creating an esp32-hal 👍 

> compile errors over runtime error
is definitely something we want

In general, looks good to me! Especially if the initial architecture fits things can be changes and extended later.

One thing I spotted: Currently some functions take clock dividers - would be more aligned with other APIs if they would take `fugit::Rate`

**Comment by bjoernQ** [comment]
Didn't get an answer to the license question, yet

> If you'd like I can add Rate taking alternatives, but I'd like to keep the divider taking ones, if that's ok :)

I see your concerns. I think a Rate taking alternative should be added since in general all the other drivers take Rate

I think it's in general not decided yet if we want to follow this "new" pattern (have the choice of using Rate _and_ naked dividers) - at least there is a comment that should have started this discussion: https://github.com/esp-rs/esp-hal/issues/174#issuecomment-1232661991

**Comment by dimpolo** [comment]
I think this is ready for review.

Let me know if and how I should squash the commits.

For the most part this should be a good starting point for the HAL. 
Things like timer sync, capturing, dead-time or carrier modulation should be easily addable in the future.

One thing I'm not sure about is how to make it possible to release the peripheral. I think you'd either have to stick a lifetime into everything or provide methods that collect all the parts. Both seem unergonomic...

**Comment by jessebraham** [comment]
Sorry for the delay, thanks for the updates. I will review the code and verify this with a logic analyzer today or tomorrow.

If you would like to squash the commits down a bit you're more than welcome to; we don't really have a policy regarding this, less than 10 would be nice I guess, but just whatever makes sense is fine. Frankly I have no problem just squashing this entire PR though, so I'll leave the choice up to you.

**Review by jessebraham — APPROVED** [review]
I've tested this using a logic analyzer and confirmed that the examples are working as expected for both the ESP32 and the ESP32-S3. The code looks quite nice to me, nothing really to say there so great job.

@bjoernQ I'd like to get your stamp of approval on this as well please before we merge.

**Comment by bjoernQ** [comment]
Code looks fine to me - well documented! Thanks for the contribution

**Comment by dimpolo** [comment]
Guess I don't squash it then, haha.
Thanks a lot for reviewing and the kind words!

**Comment by bjoernQ** [comment]
arghhh .... 🤦‍♂️

**Pull request merged**
