### PR TITLE
pulse counter implementation

### PR DESCRIPTION
**Pull request by liebman**
This is complete. I implemented this following LEDC as a guide and I'm not completely happy with the resulting API.  Some possibilities:
- implement each unit as a peripheral (PCNT0, PCNT1 etc) and initialize the clock when the first unit is configured. This would eliminate the unit::Number which is confusing with channel::Number.
- don't put the channel implementation in a separate  module.
- don't make Channel an object and just have configure_channel(ch: Channel, config: ChannelConfig) as a method on the unit.

### CODE REVIEW

**Comment by jessebraham** [comment]
So I think this is _mostly_ working. I am just using a random rotary encoder I found in my parts bin, but I'm seeing some behaviour which is (at least to me) a bit confusing, so just wanted to touch bases regarding that.

- Rotating the encoder one detent is detected by the example, however the value increments/decrements by 4; I expected the value to change by 1.
- There appears to be lower/upper limits of -100/100 set in the configuration, however when turning the encoder it happily blasts right past those values.

**Comment by liebman** [comment]
@jessebraham thanks for reviewing!
> * Rotating the encoder one detent is detected by the example, however the value increments/decrements by 4; I expected the value to change by 1.

For that type of rotary encoder if you want to count indents then you need to divide by 4. There are 4 distinct phases per indent, you can see them if you rotate very slowly between indents. I use this for attached to a motor (no indents) for odometry.

> * There appears to be lower/upper limits of -100/100 set in the configuration, however when turning the encoder it happily blasts right past those values.

Note that the hardware resets to 0 (!) when an upper or lower limit is reached.  I set the limits to +/- 100 and then track the extra as an overflow which is added to the counter value, thats why the printed result continues past 100.


I realized the other day that the control (ctrl) and interrupt enable (int_en) registers are shared across all units. I think methods that set these should called with a critical section token unless there is some better way.

**Comment by liebman** [comment]
In addition the PcntPin enum has been bugging me and was thinking about this instead, I think its a cleaner implementation.
```
/// PcntPin can be always high, always low, or an actual pin
#[derive(Clone,Copy)]
pub struct PcntSource {
    source: u8,
}

impl PcntSource {
    pub fn from_pin<'a, P: InputPin>(pin: impl Peripheral<P = P> + 'a) -> Self {
        crate::into_ref!(pin);
        Self { source: pin.number() }
    }
    pub fn always_high() -> Self {
        Self { source: ONE_INPUT }
    }
    pub fn always_low() -> Self {
        Self { source: ZERO_INPUT }
    }
}
```

**Comment by jessebraham** [comment]
Thanks for the clarification, glad to hear I was just misunderstanding this :)

**Review by jessebraham — APPROVED** [review]
Once the merge conflicts are resolved I think this is good to go, @MabezDev @bjoernQ did either of you get a chance to take a look at this?

**Comment by liebman** [comment]
> Once the merge conflicts are resolved I think this is good to go, @MabezDev @bjoernQ did either of you get a chance to take a look at this?

**Comment by jessebraham** [comment]
Ahh sorry, guess GitHub is broken for me. Says `This branch cannot be rebased due to conflicts` but my colleague has stated it does not show this for him 🤷🏻‍♂️ 

@MabezDev or @bjoernQ will have to merge this I guess.

**Comment by liebman** [comment]
@jessebraham maybe its because I merged in changes and not rebased, for some reason rebase caused huge deltas, possibly something I was doing wrong.  Maybe you can merge using a merge commit rather than a rebase?

**Comment by MabezDev** [comment]
Thanks for the PR! Seems to work well on my boards :). I did notice some odd behaviour with the example (I don't think this is a problem with the driver(?)).

> Note that the hardware resets to 0 (!) when an upper or lower limit is reached. I set the limits to +/- 100 and then track the extra as an overflow which is added to the counter value, thats why the printed result continues past 100.

Around the +-100 threshold I get some weird print outs, as seen below
image

**Comment by liebman** [comment]
@MabezDev esp32, esp32s2, or esp32s3? (so I know which example to check)

**Comment by MabezDev** [comment]
> @MabezDev esp32, esp32s2, or esp32s3? (so I know which example to check)

esp32s3

**Comment by liebman** [comment]
Thats really odd.  It implies that the interrupt is not firing.  can you try this https://gist.github.com/liebman/f3d9ee9f3b81c85e2d8e3245c6d47065 (you will need to enable a feature `esp32s3`)

**Comment by liebman** [comment]
Whats also odd is that it printed 100 as well.

**Comment by MabezDev** [comment]
Actually, that does make sense, because, inside the critical section, interrupts can't fire. So what's happening here is that the main loop enters the cs, the interrupt is pending but can't be executed, the print happens which prints 100(?) why this happens I don't know, and then the interrupt handler executes and it subtracts 100?

**Comment by liebman** [comment]
But that leads to this
```
value: 97
value: 98
value: 99
value: 0
value: 100
value: 101
```
Which I can replicate :-(.  I don't understand 1, 100, 0 unless you rotated the encoder exceedingly fast.

**Comment by MabezDev** [comment]
> unless you rotated the encoder exceedingly fast.

I did rotate it pretty fast, I got it close to the limit, and then rotated it in one movement quickly.

**Comment by liebman** [comment]
This improves but does not eliminate the race condition. (moving the print outside of the critical section when it should not have been in the first place)
```
    loop {
        let mut value: i32 = 0;
        critical_section::with(|cs| {
            let mut u0 = UNIT0.borrow_ref_mut(cs);
            let u0 = u0.as_mut().unwrap();
            value = u0.get_value() as i32 + VALUE.load(Ordering::SeqCst);
        });
        if value != last_value {
            println!("value: {value}");
            last_value = value;
        }
    }
```

**Comment by liebman** [comment]
@MabezDev - thoughts on something like: 
```
    let get_value = || {
        critical_section::with(|cs| {
            let mut u0 = UNIT0.borrow_ref_mut(cs);
            let u0 = u0.as_mut().unwrap();
            u0.get_value() as i32 + VALUE.load(Ordering::SeqCst)
        })
    };
    loop {
        // read twice and compare to insure we have a consistant result as there
        // is a race condition given that the hardware can still increment when
        // we are in a critical section.
        let mut value: i32 = get_value();
        loop {
            let value_check = get_value();
            if value == value_check {
                break;
            }
            value = value_check;
        }
        if value != last_value {
            println!("value: {value}");
            last_value = value;
        }
    }
```

**Review by MabezDev — APPROVED** [review]
Hmm so I think you're right, it seems (just through looking some idf examples) this is how to use the hw. I think it expected to use some form of debouncing for these edge cases, but for an example I don't think we need to worry about that :).

LGTM as is, thanks again!

**Pull request merged**
