### PR TITLE
Implement calibrated ADC API for S3

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [x] You updated existing examples or added examples (if applicable).
- [x] Added examples are checked in CI

### Nice to have

- [x] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

This PR implements ADC calibration on top of #555 sor the S3. The PR also defines the constants for the S2, but does not implement the example, the efuse functions or calibration types.

cc #326

### CODE REVIEW

**Comment by bugadani** [comment]
I would appreciate if someone who has the tools could test the example. I just picked some number out of thin air so it would be good to know if those are at least in the ballpark of reality.

**Comment by bjoernQ** [comment]
Code looks good to me and the raw values range also looks good. As you said would be good if someone with the appropriate equipment could verify the numbers

**Comment by bugadani** [comment]
I would appreciate if we could push this PR forward. The accuracy of the assumed VRef and other parameters may be improved later. The PR works well enough and the measured values are in the ballpark of reality (I just can't say for sure because my hardware's 1MOhm/1MOhm divider just doesn't play nice with the ADC's input impedance).

**Review by MabezDev — APPROVED** [review]
LGTM, thanks for working on this!

**Pull request merged**
