### PR TITLE
Provide ehal impls for DummyPin

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable). (does card-io count here? :D )
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

We are missing the embedded-hal impls, making the DummyPin somewhat limited. Since I don't know if InputPin makes sense on something like this, I've omitted implementing that.

### CODE REVIEW

**Review by jessebraham — APPROVED** [review]

**Comment by Dominaezzz** [comment]
> making the DummyPin somewhat limited

Isn't it supposed to be?
The differentiation doesn't exist in the hal yet (I'm looking into it in #1662) but `DummyPin` isn't really a pin, it's just a signal.
imo if people want a no-op implementation of e-hal pins, they should make their own or use a 3rd party library.

**Comment by bugadani** [comment]
It's a signal all right, and if we mandate the user to use *out* DummyPin for some cases, but require them to roll their own for other purposes, it's going to be really annoying really quickly.

**Comment by Dominaezzz** [comment]
`DummyPin` is for use within the hal, nowhere in the hal (to my knowledge 😅) does any component/driver ask for an e-hal pin.

If a user finds themselves needing a dummy e-hal pin, it's because a 3rd party driver (like embedded-emmc) is asking for one.

**Comment by bugadani** [comment]
Are you saying DummyPin should not be public at all? Or that it should not be called DummyPin and shouldn't be part of the gpio module?

**Comment by bugadani** [comment]
DummyOutput might work, sure. But I'm not sure I want to introduce a breaking change, I guess we can do that separately if the team wants to.

**Review by JurajSadel — APPROVED** [review]
Thanks!

**Review by MabezDev — APPROVED** [review]
I don't think `DummyInput` ever makes sense, because what can you return when you try and read the state? I don't think a panic is ever helpful.

Imo `DummyPin` + `impl Output` makes sense to me.

**Pull request merged**
