### PR TITLE
add Twai::enable_rx_interrupt and Twai::disable_rx_interrupt

### PR DESCRIPTION
**Pull request by dimpolo**
Tested on ESP32-S3

### CODE REVIEW

**Comment by dimpolo** [comment]
Actually I'm seeing some weird behavior so I'll convert this to a draft until I get things figured out.

**Comment by dimpolo** [comment]
So for some reason the interrupt enable register seems to have a random value at startup and needs to be reset first.

Could someone check if they're also seeing non-zero values after adding this line to a otherwise empty project?
```rust
esp_println::println!("int_ena: {:b}", peripherals.TWAI0.int_ena.read().bits());
```

**Comment by bjoernQ** [comment]
> So for some reason the interrupt enable register seems to have a random value at startup and needs to be reset first.
> 
> Could someone check if they're also seeing non-zero values after adding this line to a otherwise empty project?
> 
> ```rust
> esp_println::println!("int_ena: {:b}", peripherals.TWAI0.int_ena.read().bits());
> ```

Yes I also see some (reserved) bits set in `INT_ENA`
```
int_ena: 100001100101000000000
```

**Comment by dimpolo** [comment]
@bjoernQ thanks for having a look!

Could you try again, this time with this code?
```rust
use esp32s3_hal::twai::Instance;
esp_println::println!("int_ena 1: {:b}", peripherals.TWAI0.int_ena.read().bits());
system
    .peripheral_clock_control
    .enable(esp32s3_hal::peripherals::TWAI0::SYSTEM_PERIPHERAL);
esp_println::println!("int_ena 2: {:b}", peripherals.TWAI0.int_ena.read().bits());
```
For me the second print shows random? not reserved bits being enabled
```
int_ena 1: 110101000100000000001
int_ena 2: 1010
```
```
int_ena 1: 110101000100000000001
int_ena 2: 1001010
```
```
int_ena 1: 110101000100000000001
int_ena 2: 10001010
```
```
int_ena 1: 110101000100000000001
int_ena 2: 1010
```
```
int_ena 1: 110101000100000000001
int_ena 2: 11001010
```

**Comment by bjoernQ** [comment]
No problem - I also get seemingly random values

```
int_ena 1: 10100111010000010001
int_ena 2: 11001001
```

```
int_ena 1: 10100111000000010001
int_ena 2: 1000001
```

```
int_ena 1: 10100111000010010001
int_ena 2: 11000001
```

```
int_ena 1: 11100111000000010001
int_ena 2: 11000001
```

```
int_ena 1: 10100111000000010001
int_ena 2: 11000001
```

```
int_ena 1: 10100111010000010001
int_ena 2: 11000001
```

```
int_ena 1: 10100111000010010001
int_ena 2: 11000001
```

**Comment by jessebraham** [comment]
Thanks for your contribution! Do you have any plans to continue this work, or am I able to close this PR?

**Comment by dimpolo** [comment]
I'm planning to revisit this at some point but I'm not actively looking into it right now. Feel free to close this in the meantime.

**Pull request closed without merging**
