### PR TITLE
Switch to atomic-waker

### PR DESCRIPTION
**Pull request by MabezDev**
### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

See the discussion in #561

### CODE REVIEW

**Comment by Dirbaio** [comment]
have you actually benchmarked this? I'm a bit skeptical this will be faster, since it does a few complex atomic CAS operations.

**Comment by MabezDev** [comment]
I haven't yet, I plan on doing some rough benchmarking tomorrow. On single-core SoC's this will most likely be a bit slower, but not taking an all-core global lock (even for a short period) should be beneficial for the multicore SoCs, but we'll see tomorrow.

Another reason to switch was based on this discussion: https://github.com/esp-rs/esp-hal/issues/561#issuecomment-2053974295.

**Review by bjoernQ — APPROVED** [review]
Code looks good - I'm curious about the benchmark results

**Comment by MabezDev** [comment]
I don't have time to work on this currently so I will close this for now.

**Pull request closed without merging**
