### PR TITLE
Ensuring that the random number generator is TRNG.

### LINKED ISSUE #1120: RNG: Ensure true randomness of generated numbers
While working on #942 it turned out that the implementation of the [CryptoRng](https://docs.rs/rand_core/0.6.4/rand_core/trait.CryptoRng.html) trait implies that the generator should generate truly random numbers (be TRNG), so I looked into TRM section (check attachment) and [esp-idf implementation](https://github.com/espressif/esp-idf/blob/b3f7e2c8a4d354df8ef8558ea7caddc07283a57b/components/bootloader_support/src/bootloader_random_esp32c6.c) and it turns out that IDF does quite a few things to ensure true randomness of generated numbers. Their actions are also in line with what is written in the documentation, so I guess we also need to do make similar adjustments

image

PS: Conditions of TRNG may differ from chip to chip, but generally they're similar

### PR DESCRIPTION
**Pull request by playfulFence**
closes #1120

### CODE REVIEW

**Comment by playfulFence** [comment]
@bjoernQ - I've tried to do some "interference" tests (some basic cases, like just use both `ADC` and `RNG` peripherals) and seems to work fine...
At least if there'll be some error in those drivers we know where's the first suspect 😅

**Comment by jessebraham** [comment]
I think that the `trng` module should not exist, and that code should probably live in the `soc` module.

**Comment by playfulFence** [comment]
@jessebraham agree. Will be redesigned

**Review by MabezDev — APPROVED** [review]
LGTM, thanks for looking into this!

Long term we will want to replace the raw register writes by modifying the pacs, but we're tracking this in https://github.com/esp-rs/esp-hal/issues/1194. I think having a cryptographically secure RNG is quite important.

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Comment by playfulFence** [comment]
Rebased onto main, ready for merge

**Pull request merged**
