### PR TITLE
Add an `xtask` subcommand for building documentation

### PR DESCRIPTION
**Pull request by jessebraham**
Additionally fixes a silly mistake I made in the first PR (which I had fixed locally, but forgotten to commit 😅)

### CODE REVIEW

**Comment by jessebraham** [comment]
Oh old up, need to fix something quickly...

**Comment by jessebraham** [comment]
I'm actually going to add some more functionality as well (in-progress), so will draft this until I'm ready.

**Comment by jessebraham** [comment]
Okay this should be good to go now, I think.

**Comment by jessebraham** [comment]
Also I will actually write a proper `README.md` for it one day, I just don't want to document things while they're still in flux.

**Review by SergioGasquez — APPROVED** [review]
LGTM! The `xtask` automation looks very sweet! Thanks for assembling it

**Pull request merged**
