### PR TITLE
Improve spi master constructor

### LINKED ISSUE #890: Allow using FullDuplexMode SPI with any pin combinations (`mosi, miso, cs, ...`)
Hi!

I'm using a crate called `display-interface-spi` to drive my LCD module.
It needs trait bond `embedded_hal::blocking::spi::Write` to be satisfied.
```rust
impl<SPI, DC> SPIInterfaceNoCS<SPI, DC>
where
    SPI: hal::blocking::spi::Write<u8>,
    DC: OutputPin,
{
    pub fn new(spi: SPI, dc: DC) -> Self {
        Self { spi, dc }
    }
    
    // other methods...
}
```

I know I can call `Spi::new_half_duplex` if I want those pins to be optional, but it is *HalfDuplex* which not implement trait `embedded_hal::blocking::spi::Write`.
So, it seems like one can only use a instance created by `Spi::new` method which takes all these pins away, if that trait bond need to be satisfied?

I think there's two solutions:
 - make `Spi::new` that FullDuplexMode SPI can be used with optional pins
 - implement `embedded_hal::blocking::spi::Write` for HalfDuplexMode SPI

Maybe there's another way to do this thing?

### PR DESCRIPTION
**Pull request by sanxus**
## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [ ] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [x] You added proper docs for your newly added features and code.

Fix #890

This makes master mode spi constructor builder-like with all pins optional.

### CODE REVIEW

**Comment by sanxus** [comment]
Is this fine?

**Review by bjoernQ — APPROVED** [review]
LGTM

**Review by JurajSadel — APPROVED** [review]
LGTM

**Comment by jessebraham** [comment]
I guess we should also start updating other drivers' APIs to be consistent, if this is the pattern we'd like to use moving forward.

**Pull request merged**
