### PR TITLE
Fix QSPI

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
In half-duplex mode we shouldn't mess around with USR_MOSI/USR_MISO. I will add more tests to cover this in another PR

No CHANGELOG entry since we broke this during the current iteration

#### Testing
The `qspi_flash` example works, again

### CODE REVIEW

**Review by bugadani — APPROVED** [review]
Thanks!

**Review by MabezDev — APPROVED** [review]
Thanks!

**Comment by Dominaezzz** [comment]
It's rather strange that this works given `init_half_duplex` still "messes around" with USR_MOSI/USR_MISO.

**Comment by bjoernQ** [comment]
> It's rather strange that this works given `init_half_duplex` still "messes around" with USR_MOSI/USR_MISO.

Yeah `init_half_duplex` sets USR_MOSI/USR_MISO right and before the code unconditionally modified it

**Pull request merged**
