### PR TITLE
Convert the VS Code workspace file into a standard settings file

### PR DESCRIPTION
**Pull request by jessebraham**
We've had this workspace configuration file in the repository for a little over a year now, and I've been using it for the most part this entire time. My personal opinion is that this is not the preferable way to work on the project, and after taking another swing at a regular `.vscode/settings.json` file I seem to have gotten things working reasonably well this time around.

I've additionally added the `.vscode/extensions.json` file which will just recommend the most commonly used VS Code extensions which are useful for our project.

This seems to be working well enough based on my minimal testing, but I'll keep playing with it for awhile. If anybody has any questions/concerns/suggestions please lemme know!

### CODE REVIEW

**Comment by jessebraham** [comment]
(No changes to `CHANGELOG.md` required, forgot the label...)

**Comment by bjoernQ** [comment]
I never used the VS code workspace and probably won't use this since I'm happy with my workflow (which is based on generating `.vscode/settings.json` with correct features etc. per crate)

But I'd say we should change `.vscode` to `**/.vscode` in `.gitignore` to keep me (and others) from checking in their VSCode settings in the subfolders

Probably someone who used the VS code workspace before should test if this makes things better

**Comment by MabezDev** [comment]
I can't seem to get this to work, as much as I would like it to :(. My main issue is the the esp-hal-common build script can't be run by rust-analyzer

```
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: Features "embassy-time-systick" and "embassy-time-timg0" cannot be used together
   --> /home/mabez/development/rust/embedded/hal/esp-hal/esp-hal-common/build.rs:19:13
    |
19  |             compile_error!(concat!("Features \"", $first, "\" and \"", $rest, "\" cannot be used together"));
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
169 |         assert_unique_used_features!("embassy-time-systick", "embassy-time-timg0");
    |         -------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `assert_unique_features` which comes from the expansion of the macro `assert_unique_used_features` (in Nightly builds, run with -Z macro-backtrace for more info)


error[E0428]: the name `main` is defined multiple times
  --> build.rs:82:1
   |
20 | fn main() {
   | --------- previous definition of the value `main` here
...
82 | fn main() {
   | ^^^^^^^^^ `main` redefined here
   |
   = note: `main` must be defined only once in the value namespace of this module


error: Features "mcu-boot" and "direct-boot" cannot be used together
  --> build.rs:11:13
   |
11 |             compile_error!(concat!("Features \"", $first, "\" and \"", $rest, "\" cannot be used together"));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
17 | assert_unique_features! {"mcu-boot", "direct-boot"}
   | --------------------------------------------------- in this macro invocation
   |
   = note: this error originates in the macro `assert_unique_features` (in Nightly builds, run with -Z macro-backtrace for more info)


error: aborting due to 2 previous errors


For more information about this error, try `rustc --explain E0428`.

error: could not compile `esp32c3-hal` (build script) due to 3 previous errors
error: aborting due to previous error


error: could not compile `esp-hal-common` (build script) due to 2 previous errors
```

because of this, rust-analyzer doesn't understand any of our custom cfgs and that makes go to definition etc not work very well. Any ideas how to solve that?

**Comment by jessebraham** [comment]
No idea, not having that problem. Working as expected on my end.

**Comment by MabezDev** [comment]
Omfg I had an all features setting enabled globally in my user vscode settings :facepalm:. It now works!

**Comment by MabezDev** [comment]
Re-opening for further discussion, sorry for being a dummy @jessebraham!

**Pull request merged**
