### PR TITLE
Add I2S HIL test

### PR DESCRIPTION
**Pull request by bjoernQ**
ESP32 and ESP32-S2 are not tested since I wasn't able to get it to work there.

However, this test might be really helpful since it's the only test where circular DMA is tested. Also, I2S tends to be hard to test manually

### CODE REVIEW

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!
Regarding ESP32 and S2, it's `i2s` or `hil` related issue?

**Comment by bjoernQ** [comment]
> LGTM, thanks! Regarding ESP32 and S2, it's `i2s` or `hil` related issue?

I2S ... I wasn't able to get loopback working there. But since especially a lot of DMA code is shared it's still very helpful for those targets

**Review by SergioGasquez — APPROVED** [review]
LGTM! Tried it on H2 and it passes, the only thing is that its a bit slow (~1 min):
```
      Erasing ✔ [00:00:00] [#] 192.00 KiB/192.00 KiB @ 520.69 KiB/s (eta 0s )
  Programming ✔ [00:00:00] [####] 37.88 KiB/37.88 KiB @ 67.90 KiB/s (eta 0s )    Finished in 0.954s

running 1 test
test tests::test_i2s_loopback ... ERROR probe_rs::util::rtt:
Error reading from RTT: The control block has been corrupted. write pointer is 2652638602 while buffer size is 1024 for up channel 0 (defmt)
ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 57.67s
```

**Comment by bjoernQ** [comment]
Awesome .... the frequency on H2 is apparently so slow it takes forever to transmit the data. Will disable the test for H2 here and open an issue

**Comment by SergioGasquez** [comment]
> Awesome .... the frequency on H2 is apparently so slow it takes forever to transmit the data. Will disable the test for H2 here and open an issue

Feel free to add it here https://github.com/esp-rs/esp-hal/issues/1524 if you prefer

**Review by MabezDev — APPROVED** [review]
Thanks!

**Comment by MabezDev** [comment]
Sorry, let's just disable that interrupt test. I have no idea was is introducing the variability in the latency.

**Pull request merged**
