### PR TITLE
Add support for the ESP32-C2/ESP8684

### PR DESCRIPTION
**Pull request by jessebraham**
Apologies for the size of this PR 😁 

As per the title, adds support for the ESP32-C2/ESP8684. The SVD/PAC are still missing a peripheral or two (I think it's just `LEDC` but I could have missed more), but this covers most of the hardware. 

The `i2c_display` example has not been tested, as I don't have this display. @bjoernQ can you please try it out? I have tested all of the remaining examples and their behaviour is consistent with the other devices. This has not been thoroughly tested, however.

The CI config is still a bit janky and will need to be fixed eventually, but it works for now so I'm not going to worry about it.

This has been rebased a number of times, so there may be some artifacts from that. I think I've caught them all, but something to keep in mind.

### CODE REVIEW

**Comment by bjoernQ** [comment]
I2C doesn't seem to really work yet

ssd1306

image

image

**Comment by bjoernQ** [comment]
There are a couple of unused constants in `src\clocks_ll\esp32c2.rs` ... doesn't make sense to manually mark them all in the code

**Comment by bjoernQ** [comment]
Besides the things mentioned above this already looks good to me. For I2C we could also note it's not working yet and deactivate the example until we figure out what is wrong

**Comment by jessebraham** [comment]
> There are a couple of unused constants in `src\clocks_ll\esp32c2.rs` ... doesn't make sense to manually mark them all in the code

Oops, meant to remove those and forgot. Thanks for pointing it out, they're gone now.

> Besides the things mentioned above this already looks good to me. For I2C we could also note it's not working yet and deactivate the example until we figure out what is wrong

I'll spend a bit of time today looking into the `I2C` issues, if I can't get them resolved then I'll probably take this approach. I'd like to get this PR wrapped up sooner than later, I've been rebasing/maintaining it for some time now waiting for the last bits of the TRM to become available 😁

**Review by MabezDev — APPROVED** [review]
A lot to unpack here, I mainly focused on the linker scripts which look fine to me! Everything else seems to be clock control or glue code into existing drivers.

Yay for C2 support! :tada:

**Comment by jessebraham** [comment]
The issues with `I2C` still persist, but I'm going to merge this regardless. Overall it's _mostly_ working, and all the examples are building in CI, so close enough for now 😁  I'll open an issue so we don't forget to fix it.

**Pull request merged**
