### PR TITLE
Add support for splitting esp32 uart into TX and RX

### PR DESCRIPTION
**Pull request by Georges760**
* Keeps existing API for uart, but wraps it in Tx and Rx sub-types
* Adds split() method similar to embassy-rs nRF/stm32/rp for getting indepdendent TX and RX parts
* Implements e-h traits for TX and RX types
* Add esp32s3 example

## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [x] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [x] You updated existing examples or added examples (if applicable).
- [x] Added examples are checked in CI

### Nice to have

- [x] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

### CODE REVIEW

**Comment by Georges760** [comment]
Do anyone know why the Instance type is not propagated to UartFuture in the new() constructor ?

It is well propagated from Uart to UartRx and UartTx in their new_inner() contructor.

Is it because UartFuture lives in a sub mod Asynch ?

**Comment by MabezDev** [comment]
Sorry, missed this completely!

To fix the current compilation errors, you just need to specify that the `T` used by the `UartFuture` is the same `T` from the `UartRx/Tx`. I.e `UartFuture::new(` => `UartFuture::<T>::new(`. This seems to be a quirk of async Rust, as normal functions can infer this usually.

**Comment by Georges760** [comment]
why do my cargo fmt is not the same as the one from CI ?

**Review by MabezDev — CHANGES_REQUESTED** [review]
This is looking good functionality wise, but could we improve the example? What about sending the read bytes over a channel to the write to be written back out? As it stands the example isn't very interactive. We can also drop the AT command stuff for this example.

**Comment by Georges760** [comment]
> Another alternative would be to instead of adding a new example, change the current embassy_serial one to use split by default.

OK I will do that. Sorry I have very few time for this now...

**Comment by Georges760** [comment]
i did mess up my repo while rebasing, and this close the PR. I will open a new one, sorry

**Review by MabezDev — APPROVED** [review]
Thanks @Georges760! LGTM!

**Pull request merged**
