### PR TITLE
rsa peripheral support

### PR DESCRIPTION
**Pull request by matrixhead**
this pr adds support for rsa peripheral, i would love to hear your thoughts on this also i tested it only  in esp32  so i'm not sure this is working on other chips.

### CODE REVIEW

**Review by MabezDev — CHANGES_REQUESTED** [review]
Looking really good so far, thanks for the PR! I've tested on ESP32, ESP32-C3 & ESP32-S3 and it seems to work well so far.

CI needs fixing, could you:
  - Run rustfmt across the project
  - either bump the msrv to 1.67 or use a different solution than `ilog2` etc

One final thing, and this is optional, but it would be nice to have a small benchmark vs some software solution, like we do for the other crypto examples.

**Comment by matrixhead** [comment]
@MabezDev thanks 😀 i will try to do these

**Review by MabezDev — APPROVED** [review]
Thanks for this! Looks great!

**Review by bjoernQ — APPROVED** [review]
LGTM!
Thanks for your contribution

**Pull request merged**
