### PR TITLE
Support lld linker

### PR DESCRIPTION
**Pull request by MabezDev**
Adds LLD support for all Xtensa chips (Direct boot scripts not yet changed for s3). 

To test just comment the GNU parts and uncomment the LLD parts. You'll need a copy of Xtensa enabled lld from here: https://github.com/espressif/llvm-project/releases/tag/esp-15.0.0-20221201. If you try and build it will tell you where you need to copy the executable, and remember to rename it to `rust-lld`! In the future you won't need to bother with this as we will ship with the toolchain.

To add some context to the changes, I'll break them down into two parts. The first part is straightforward, LLD does not have the same semantics when using absolute addresses inside sections, see https://github.com/esp-rs/xtensa-lx-rt/pull/52 for more details. The second part is where it gets interesting. We have some [hand-rolled assembly inside](https://github.com/esp-rs/xtensa-lx-rt/blob/7324ef0b47ec1d1c341f9914a9f262b76770a099/src/exception/assembly_esp32.rs#L576) that handles interrupts. Part of that code is responsible for setting the processor state (`PS` special register)  which looks like `movi    a0, (\level | PS_WOE)`. `PS_WOE` is just something we need to enable to allow the window ABI to work correctly, the level is the current interrupt level, e.g 1. The resultant value of this is `0x40001`. The `movi` instruction can only hold values up to 2048 (see below), so the assembler does something clever. It "relaxes" the `movi` instruction to a `l32r` instruction. The `l32r` allows reading a 32-bit value from memory (known as a literal), with a **negative** offset from the _current_ program counter value; because the offset must be negative, this means the literal we want to read **MUST** be placed before the code that wishes to read it! Hence the literals section placement now comes before the text section definitions and allows the program to run correctly. So why did the original scripts work with the GNU toolchain? It worked because there is a flag that is enabled by default called `text-section-literals` which merges the literal and text sections and ensures the relevant literals are placed before the reference to them in the code.

image
image

### To Do

- [x] Update `xtensa-lx-rt` dependency once a new version has been published
- [ ] Update the direct-boot linker scripts for the ESP32-S3

### CODE REVIEW

**Comment by bjoernQ** [comment]
Thanks for the detailed writeup - the changes now make perfect sense to me

Just need to try it and it should be fine from my side

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks for taking care of this

Only inconvenience on Windows was it also needs `libLLVM-15.dll` besides `lld.exe` renamed to `rust-lld.exe`

**Comment by MabezDev** [comment]
> LGTM - Thanks for taking care of this
> 
> Only inconvenience on Windows was it also needs `libLLVM-15.dll` besides `lld.exe` renamed to `rust-lld.exe`

Once we ship LLD with our Rust toolchain that dependency issue should be solved :).

**Comment by jessebraham** [comment]
Converted this to a draft so it doesn't accidentally get merged before the two points I added to the original comment are resolved. I'll take a look at this either today or tomorrow.

**Comment by jessebraham** [comment]
Sorry, as you can tell I completely forgot about this. Will try to revisit it in the next week or two here.

**Comment by jessebraham** [comment]
This seems to be working! So once this is rebased and the direct-boot linker scripts for the S3 have been updated I see no reason not to merge this.

**Comment by MabezDev** [comment]
Xtensa LLD is still not ready for use at the moment, and our linker scripts have diverged a lot since this PR, so I will close this and open a new one once LLD is ready.

**Pull request closed without merging**
