### PR TITLE
Fix docs.rs link in esp-wifi/README.md

### PR DESCRIPTION
**Pull request by jonasspinner**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
I fixed the docs.rs link in the README.md of the esp-wifi crate.

#### Testing
Clicking the badge leads to the correct docs.rs page.

### CODE REVIEW

**Comment by bjoernQ** [comment]
Thanks! The link is indeed broken. I think we want to link to our self-hosted docs like https://docs.esp-rs.org/esp-hal/esp-wifi/0.6.0/esp32/esp_wifi/ - we don't have an esp-wifi landing page so probably we should just link to https://docs.esp-rs.org/esp-hal/ for now

Probably it wouldn't need a CHANGELOG.md entry

**Comment by jonasspinner** [comment]
Thank you for your feedback. I removed the CHANGELOG.md entry and changed the link to https://docs.esp-rs.org/esp-hal/ as suggested.

The other crates in this repository link to their https://docs.rs page. For example:
https://github.com/esp-rs/esp-hal/blob/921ecc4d561e6dbd880c27aa89f63a33e02379fd/esp-alloc/README.md?plain=1#L4

While checking that, I have found that two crates have broken links for crates.io, docs and license, [esp-ieee802154](https://github.com/esp-rs/esp-hal/blob/921ecc4d561e6dbd880c27aa89f63a33e02379fd/esp-ieee802154/README.md) and [esp-lp-hal](https://github.com/esp-rs/esp-hal/tree/921ecc4d561e6dbd880c27aa89f63a33e02379fd/esp-lp-hal/README.md). But I think that they currently unpublished.

**Comment by bjoernQ** [comment]
👍 

Yes, the links for the unpublished crates will be fine once they are published (which we plan to publish with the next release)

The smaller crates usually don't really have different API depending on the target so users can just use docs.rs. We might self-host their docs in future, too but it's not planned yet

**Review by bjoernQ — APPROVED** [review]
LGTM

**Review by JurajSadel — APPROVED** [review]
LGTM

**Pull request merged**
