### PR TITLE
Remove unnecessary delay

### PR DESCRIPTION
**Pull request by SergioGasquez**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
In ESP-IDF (using S3), the equivalent method is https://github.com/espressif/esp-idf/blob/5ca9f2a49aaabbfaf726da1cc3597c0edb3c4d37/components/esp_hw_support/port/esp32s3/rtc_sleep.c#L174 which is then called in https://github.com/espressif/esp-idf/blob/5ca9f2a49aaabbfaf726da1cc3597c0edb3c4d37/components/esp_hw_support/sleep_modes.c#L926.

There is no delay in the ESP-IDF source code, so I think we could delete it. 

#### Testing
Not tested yet

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM - I _think_ originally that delay was to make it likely that the UART is fully flushed before sleeping - but the user can do that (which the examples show)

**Review by MabezDev — APPROVED** [review]
Thanks for looking into this, LGTM!

**Review by playfulFence — CHANGES_REQUESTED** [review]
LGTM, thanks!
Just a small one, it appears in the updated examples.

image

**Comment by SergioGasquez** [comment]
> LGTM, thanks! Just a small one, it appears in the updated examples.
> 
> image

Good catch! Fixed them

**Review by playfulFence — APPROVED** [review]
Thanks a lot!

**Pull request merged**
