### PR TITLE
Add missing `#[doc(hidden)]` attributes for embassy proc macros

### PR DESCRIPTION
**Pull request by AnthonyGrondin**
Fixes https://github.com/esp-rs/esp-hal/issues/1233

### CODE REVIEW

**Comment by AnthonyGrondin** [comment]
I forgot to edit the changelog, but I don't know if we really need a changelog entry for this.

**Review by bjoernQ — APPROVED** [review]
LGTM

**Comment by bjoernQ** [comment]
> I forgot to edit the changelog, but I don't know if we really need a changelog entry for this.

I guess we don't really need it. But maybe someone else thinks different of that?

**Review by JurajSadel — APPROVED** [review]
LGTM

**Comment by jessebraham** [comment]
Sorry for the CI issues, mind giving this a quick rebase to resolve them?

**Comment by jessebraham** [comment]
Oh neat, I can just click a button and rebase it myself now 😁

**Review by jessebraham — APPROVED** [review]
Thanks!

**Pull request merged**
