### PR TITLE
ESP32-S3 deep sleep

### PR DESCRIPTION
**Pull request by bugadani**
This PR adapts #574 for the ESP32-S3. The PR also includes some minor changes to the ESP32 implementation based on esp-idf.

cc #375

### CODE REVIEW

**Comment by bugadani** [comment]
esp-idf's `rtc_init`, which is the basis of `base_settings` seems to have a bunch of code that should run on startup (LDO bias settings for example). I am unsure how to approach those. Currently, everything is part of `base_settings` but I'm fairly certain that applying a low LDO bias for sleep could actually not let the MCU wake up properly, in a stable manner.

This probably means we'll need to tie some of the sleep infra into clock initialization, for example.

**Comment by bugadani** [comment]
I have hijacked `RtcSleepConfig` a bit to actually implement MCU-specific sleep logic, partitioned somewhat similarly to esp-idf: by including a `start_sleep` and a `finish_sleep` function. I've moved the register access code from the parent module into `RtcSleepConfig`, hopefully this will help more in terms of MCU support than it hurts by requiring duplication.

**Review by MabezDev — APPROVED** [review]
LGTM, works for me so I see no reason not to merge this as is. Thanks for looking into this!

**Comment by bugadani** [comment]
> works for me

oh wow I didn't actually test this because I need to implement GPIO wakeup for my stuff, but that's great to hear!

**Pull request merged**
