### PR TITLE
Check missing `embassy_XX` examples to the CI

### PR DESCRIPTION
**Pull request by JurajSadel**
## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [x] All examples work.
- [x] `cargo fmt` was run.
- [ ] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

### CODE REVIEW

**Review by jessebraham — APPROVED** [review]
LGTM, thanks! I still think we need to re-visit our CI jobs for these packages, but for the time being this puts us in much better shape than we were in, at least 😁

**Comment by JurajSadel** [comment]
While working on this PR I was thinking about going from `cargo check` to `cargo build` - but it requires more changes - does it make sense to invest time into this change or not? :D

**Comment by jessebraham** [comment]
We should be using `cargo build`, sorry I missed that. If you want to change it in this PR feel free, if not don't worry about it (as I said, we will be updating the CI workflow again anyway)

**Comment by JurajSadel** [comment]
I can look into that but I would prefer to do it in a separate PR.

**Review by SergioGasquez — APPROVED** [review]
LGTM!

Edit: a bit late to the party, are we still evaluating doing the https://github.com/esp-rs/esp-hal/pull/900 approach?

**Pull request merged**
