### PR TITLE
Add support for 80Mhz psram, selected using 'psram-80mhz' feature

### PR DESCRIPTION
**Pull request by yanshay**
Added support for 80Mhz PSRAM Bus as discussed in #1069

## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

### CODE REVIEW

**Comment by bjoernQ** [comment]
Thanks! This seems to work fine for me

However, the new features need to get documented here: https://github.com/esp-rs/esp-hal/blob/6afc988f886a00d9e78ed07450ec9226af7bfbad/esp32s3-hal/src/lib.rs#L8-L45

Also, we should mention there that it's for qspi RAM only, currently

**Comment by yanshay** [comment]
> Also, we should mention there that it's for qspi RAM only, currently

I can add it to the qspi as well, it should work. Where I read about this it was in context of qspi, but I can't test it to work. To add it there as well?

**Comment by bjoernQ** [comment]
> > Also, we should mention there that it's for qspi RAM only, currently
> 
> I can add it to the qspi as well, it should work. Where I read about this it was in context of qspi, but I can't test it to work. To add it there as well?

Yes, that would also be good. I don't think I have hardware to test 80MHz OSPI but the code would support it

**Comment by yanshay** [comment]
Added 80Mhz suppoort to octal psram and documetnation to lib.rs

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
