### PR TITLE
pub UartRx read_byte

### LINKED ISSUE #1547: UartRx's read_byte should be public
[At uart.rs, line 466](https://github.com/esp-rs/esp-hal/blob/2c1e66e9b38faa6194eb03315eb6d27fe679f96a/esp-hal/src/uart.rs#L467), this function should be public:

```rust
impl<'d, T, M> UartRx<'d, T, M>
where
    T: Instance,
    M: Mode,
{
    pub fn read_byte(&mut self) -> nb::Result<u8, Error> {
        // On the ESP32-S2 we need to use PeriBus2 to read the FIFO:
        let offset = if cfg!(esp32s2) { 0x20C00000 } else { 0 };

        if T::get_rx_fifo_count() > 0 {
            let value = unsafe {
                let fifo = (T::register_block().fifo().as_ptr() as *mut u8).offset(offset)
                    as *mut crate::peripherals::generic::Reg<FIFO_SPEC>;
                (*fifo).read().rxfifo_rd_byte().bits()
            };

            Ok(value)
        } else {
            Err(nb::Error::WouldBlock)
        }
    }
}
```

Or you should change the document for [uart.rs at line 44](https://github.com/esp-rs/esp-hal/blob/2c1e66e9b38faa6194eb03315eb6d27fe679f96a/esp-hal/src/uart.rs#L61):

```rust
//! ### Examples
//!
//! #### Sending and Receiving Data
//!
//! ```no_run
//! // Write bytes out over the UART:
//! uart1.write_bytes("Hello, world!".as_bytes())?;
//! ```
//!
//! #### Splitting the UART into TX and RX Components
//!
//! ```no_run
//! // The UART can be split into separate Transmit and Receive components:
//! let (mut tx, rx) = uart1.split();
//!
//! // Each component can be used individually to interact with the UART:
//! tx.write_bytes(&[42u8])?;
//! let byte = rx.read_byte()?;
//! ```
```

just a tiny fix so I have given a pr, you can accept or fix with other change

### PR DESCRIPTION
**Pull request by nan-mu**
Detail in https://github.com/esp-rs/esp-hal/issues/1547

EDIT by Kirill: closes #1547

### CODE REVIEW

**Comment by bjoernQ** [comment]
Thanks! Making `read_byte` public is fine but there are a few problems with this PR

- public functions should include API docs
- this adds a changelog in the root - the changelog entry should go into `esp-hal/CHANGELOG.md`
- code formatting

**Comment by nan-mu** [comment]
The issue has been resolved. I hadn't previously worked with these tools, so I'm thankful; I've learned a lot.

**Comment by nan-mu** [comment]
The issue has been resolved. I hadn't previously worked with these tools, so I'm thankful; I've learned a lot.

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by playfulFence — APPROVED** [review]
LGTM and thanks for your commit!

**Pull request merged**
