### PR TITLE
Simplify rmt channels by turning `Channel0<0>` into `Channel<0>`

### PR DESCRIPTION
**Pull request by jneem**
This may be a Chesterton's fence situation, but I couldn't figure out why we have `Channel0<0>` and `Channel0Creator<0>` instead of just `Channel<0>` and `ChannelCreator<0>`. 

I've tested that esp32c3 still works; I don't have other chips to test.

- [x] The code compiles without `errors` or `warnings`.
- [x] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [x] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

### CODE REVIEW

**Comment by bugadani** [comment]
I don't know anything about RMT, but I wonder if instead of documenting which channel does tx vs rx, could the implementation be split into `TxChannel<N>` and `RxChannel<N>`? At that point I believe the private inner traits could be replaced by inherent implementations if the channels have the same capabilities.

**Comment by jneem** [comment]
I'm not sure if this is what you meant, but tx vs rx isn't just enforced by documentation: the `TxChannel` and `RxChannel` traits that are only implemented by the appropriate channels.

I do think it's useful to have the `TxChannel` and `RxChannel` traits because it allows you to easily write code that works with any `TxChannel`, but I'll have a look to see if the private inner traits can be simplified...

**Comment by bugadani** [comment]
> I'm not sure if this is what you meant, but tx vs rx isn't just enforced by documentation: the TxChannel and RxChannel traits that are only implemented by the appropriate channels

True but for a user it's not immediately obvious which channel does what.

> I do think it's useful to have the TxChannel and RxChannel traits because it allows you to easily write code that works with any TxChannel

Yeah I missed something important here, sorry :) I was thinking const-generics would allow this: `fn foo<const CH: RmtChannel>(ch: TxChannel<CH>) { ... }`, but unfortunately not until enums can be const generic parameters.

**Review by jessebraham — APPROVED** [review]
Thanks for this! I think everything looks okay (a bit hard to review due to the macro usage, but that's hardly your fault 😁 ). Would just like to get another set of eyes on it before merging to be safe.

**Review by bjoernQ — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
