### PR TITLE
spi pac update

### PR DESCRIPTION
**Pull request by burrbull**
For https://github.com/esp-rs/esp-pacs/pull/224

### CODE REVIEW

**Comment by burrbull** [comment]
Not sure about second commit. Need tests
cc @MabezDev

**Comment by MabezDev** [comment]
I did a HIL test run (only C6 right now): https://github.com/esp-rs/esp-hal/actions/runs/8801550864/job/24155269572, looks like it passed :)

**Comment by burrbull** [comment]
rebased

**Review by MabezDev — APPROVED** [review]
LGTM, thank you!

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
