### PR TITLE
Implement sleep and wakeup functionalities for ESP32C2

### PR DESCRIPTION
**Pull request by M4tsuri**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

Added sleep and wakeup support for esp32c2. Most codes are copied from the esp32c3 implementation and changed according to esp-idf. Related issue #1920 

#### Testing

Both examples `sleep_timer` and `sleep_timer_rtcio` work fine on my ESP32C2 dev board. I'll test this more thoroughly later.

### CODE REVIEW

**Comment by jessebraham** [comment]
Just checking in here, would you like us to find somebody to test and, if needed, wrap up this PR for you? Or do you still intend to come back to this?

**Comment by M4tsuri** [comment]
Sorry that I was occupied with something else after this PR. But I plan to use this feature in our product so I'm going to come back to this PR maybe next week. Of course it would be better of someone else can also do a test since I'm actually not that familiar with technical details of these sleep modes.

**Comment by bjoernQ** [comment]
Just ran the two examples on a 40MHz and a 26MHz xtal ESP32-C2 and they both seem to work fine

**Comment by M4tsuri** [comment]
Thank you, that's good. Maybe I should mark it as ready now.

**Review by jessebraham — APPROVED** [review]
Example is working and changes LGTM, thank you for getting this wrapped up!

**Review by bugadani — APPROVED** [review]
Thank you

**Pull request merged**
