### PR TITLE
gpio: DummyPin + hub75_i8080 example

### PR DESCRIPTION
**Pull request by liebman**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### Pull Request Details 📖
DummyPin for when you don't want/have a real Pin.

#### Description
This PR adds DummyPin.  Useful in cases where you have to supply a pin but it wont really be used, like `esp_hal::lcd_cam::lcd::i8080::TxSixteenBits` but you only want 14 bits.  The included example does exactly this driving a HUB75 LED Matrx display using the lcd_cam peripheral.

#### Testing
Tested on esp32s3 with the new example.

### CODE REVIEW

**Comment by liebman** [comment]
image

**Review by bjoernQ — APPROVED** [review]
I can't test the example but the dummy pin is useful

**Review by JurajSadel — APPROVED** [review]
LGTM, I also don't have a way of testing the example, I will ask, if someone from the team could give it a try. Thanks!

**Review by MabezDev — CHANGES_REQUESTED** [review]
Thanks for the PR! I like the dummy pin, but I think the example is probably not required. We won't be able to test it and it will likely bit rot over time. Could you remove it?

**Review by MabezDev — APPROVED** [review]
Thank you!

**Pull request merged**
