### PR TITLE
Add initial ADC/GPIO implementation for ESP32-H2

### PR DESCRIPTION
**Pull request by jessebraham**
@SergioGasquez was able to test and verify the example on hardware for me. Still need the AF signals and what not, but gives us a base to build off of at least.

(A passing CI run can be found [here](https://github.com/jessebraham/esp-hal/actions/runs/4810495010))

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
Code looks good to me! Cannot verify it on hardware currently

**Comment by JurajSadel** [comment]
I'll verify on real HW tomorrow (I don;t have H2 with me at the moment :D )

**Comment by jessebraham** [comment]
@bjoernQ fair enough, that's been reverted. Not sure why I changed it in the first place TBH 🤷🏻‍♂️ 

ADC stuff is just sort of intermingled with the GPIO stuff, so I included those bits. Didn't test or anything, guess I could remove it but I think it's fine to include for now.

**Review by JurajSadel — APPROVED** [review]
LGTM, both examples (`hello_world` and `blinky`) work on real H2 chip correctly.
We have some warnings 
```rust
warning: unused variable: `system`
   --> /home/ubuntu/esp-hal/esp-hal-common/src/system.rs:502:13
    |
502 |         let system = unsafe { &*SystemPeripheral::PTR };
    |             ^^^^^^ help: if this is intentional, prefix it with an underscore: `_system`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `peripheral`
   --> /home/ubuntu/esp-hal/esp-hal-common/src/system.rs:501:30
    |
501 |     pub fn enable(&mut self, peripheral: Peripheral) {
    |                              ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_peripheral`

warning: `esp-hal-common` (lib) generated 2 warnings (run `cargo fix --lib -p esp-hal-common` to apply 2 suggestions)
warning: unused variable: `clocks`
  --> examples/hello_world.rs:17:9
   |
17 |     let clocks = ClockControl::configure(system.clock_control, CpuClock::Clock96MHz).freeze();
   |         ^^^^^^ help: if this is intentional, prefix it with an underscore: `_clocks`
   ```
   
   but I guess we will clear them along the way.

**Review by MabezDev — APPROVED** [review]
LGTM! Can't test, but the code looks fine to me.

**Pull request merged**
