### PR TITLE
Add Flex/AnyFlex pin drivers

### LINKED ISSUE #740: Treat a Gpio pin as either input or output.
I'm trying to implement a bit-bang controller for a peripheral (ADNS5050, specifically), based an CPP arduino code.

The problem I've run into, is that I need to be able to use one of the pins as both input and output. If there's an ergonomic/intuitive way to do this as things already are, I've missed it.

Ideally, I'd be able to write something like this:

```rust
struct ADNSDriver<'a, MODE>
{
    sdio: &'a mut dyn IOPin<Error = Infallible, MODE>,
    srl_clk: &'a mut dyn OutputPin<Error = Infallible>,
    not_reset: &'a mut dyn OutputPin<Error = Infallible>,
    not_chip_sel: &'a mut dyn OutputPin<Error = Infallible>,
    pix: [u8; 360],
}
```
Reason being, is I have code a bit like this:
```rust
    fn read_reg(&mut self, addr: ADNSRegs, delay: &mut Delay) -> u8 {
        let stdio_writer = self.sdio.into_push_pull_output();
        let mut addr = addr as u8;
        for _ in 0..8 {
            // use bit-banging to write with the sdio pin as an output
            // in order to choose which memory address to read from
        }

        let mut res = 0u8;

        for i in 0..8 {
            // use bit-baning to read from the sdio-pin as an InputPin in order to get the value at
            // that memory address
        }

        res
    }
```

...the ADNSDriver can use the `sdio` field _either_ an output pin XOR an input pin. If there's a way to dance between the two modes in a nice way, I been unable to come across it.

Context: https://github.com/rust-embedded/embedded-hal/issues/357 in short: `embedded-hal` has the `IoPin` trait as well as some others, but is removing it for `1.0.0` (follow link for details).

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
This adds a Flex/AnyFlex pin driver to fix #740 

#### Testing
The GPIO HIL-test exercises the new driver. Doesn't seem to deserve a dedicated example

### CODE REVIEW

**Review by MabezDev — APPROVED** [review]
This is excellent, thanks for working on this! Very nice PR.

LGTM!

**Comment by jessebraham** [comment]
I think we need much more documentation in this module. Looking at the docs with this branch included:

Screenshot 2024-06-05 at 06 23 40

I can't even imagine trying to figure out which pin type I need as a user who is not familiar with the HAL. I don't even really know what half of these types do, honestly.

**Comment by bjoernQ** [comment]
> I can't even imagine trying to figure out which pin type I need as a user who is not familiar with the HAL. I don't even really know what half of these types do, honestly.

I have a few ideas for improving the docs here and also on the "landing page" to help new users to have a smooth(er) start. But well - not in this PR (and we should generally wait for the doc-test PR to land before shuffling around docs I guess)

But it's definitely already much easier than the `into_XXX` API we had before

**Comment by bjoernQ** [comment]
I think the docs topic touches #742

**Comment by MabezDev** [comment]
I opened https://github.com/esp-rs/esp-hal/issues/1660 to track the module level doc improvements

**Pull request merged**
