### PR TITLE
Peripheral ref/gpio

### PR DESCRIPTION
**Pull request by MabezDev**
The final update in this conversion step.

A couple of things had to change to get this working:

- I2S pin structs now have constructors
- MSRV bumped to 1.65 because pulse control traits now use GATs

I *think* I've covered everywhere we use pins but I would appreciate a triple-check on that.

### CODE REVIEW

**Comment by SergioGasquez** [comment]
Shouldn't we also update `rust-version` in `Cargo.toml`s (`esp-hal-common` and for every chip)?

**Comment by MabezDev** [comment]
> Shouldn't we also update `rust-version` in `Cargo.toml`s (`esp-hal-common` and for every chip)?

Good spot, thanks! Will update those too.

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for taking care of it!

**Review by JurajSadel — APPROVED** [review]
LGTM!

**Comment by bjoernQ** [comment]
Awesome work! Thank you!

There are two things I was wondering about before I wanted to have a take on this:
- some drivers (e.g. SPI) only configure the pins and not store the reference/the pin
    - when moving the pin nothing changes (not ideal since the pin is gone but that's how it was) but when using a mutable reference, the user could use the pin afterwards for something else
 - the `into_XXX` functions consume the pin - is this an issue?

To be honest I don't have a solution for the second issue at hand but both can be tackled in upcoming PR(s)

In theory because of the first issue, it's possible to use the pins in an unsound way but that situation will get fixed soon - so I'm not too concerned

**Review by jessebraham — APPROVED** [review]
Ditto to what @bjoernQ said but overall LGTM!

**Comment by MabezDev** [comment]
> some drivers (e.g. SPI) only configure the pins and not store the reference/the pin
when moving the pin nothing changes (not ideal since the pin is gone but that's how it was) but when using a mutable reference, the user could use the pin afterwards for something else

I thought about this too, but I checked and the borrow still lasts even if the `PeripheralRef` isn't stored. There are also a few embassy drivers which do the same thing, so if it turns out to be broken or breaks in the future I'm sure we'll know about it :D.

> the into_XXX functions consume the pin - is this an issue?

I _don't think_ its an issue because the `Peripheral` [implementation is generic](https://github.com/esp-rs/esp-hal/pull/323/files#diff-5cfc259c51ff612ad7e3c9c3e9ea5eb7403058abec590ba9ca6811a0eb59b30cR910-R921) over whatever mode / config the pin is in so even though the into functions consume the pin, the resultant pin should still implement `Peripheral`.

**Pull request merged**
