### PR TITLE
Introduce optional ufmt support

### PR DESCRIPTION
**Pull request by DoumanAsh**
Subj
This implementation, while lacking most of core's fmt capabilities, provides optimized for size implementation that allows minimal viable formatting

I also took liberty to expose writing as common function to allow user to use, if he would need.
let me know if you want to hide it.

### CODE REVIEW

**Comment by MabezDev** [comment]
@jessebraham @bjoernQ looks like some CI issue, wrong CI build artifacts being cached maybe?

**Comment by bjoernQ** [comment]
Yes looks like a caching issue to me

**Comment by bjoernQ** [comment]
Agreed - let's merge this! For the CI builds: maybe we need to somehow use the version of the Rust compiler as a cache key?

**Comment by jessebraham** [comment]
Yeah not a bad idea at all, I will try to make some improvements to the `xtensa-toolchain` action to try and detect this condition as some point.

**Pull request merged**
