### PR TITLE
i2c: implement `I2C:transaction` for  `embedded-hal` and `embedded-hal-async`

### LINKED ISSUE #1490: i2c peripheral is not using a repeated start condition for `write_read()`
A logic analyser shows that a stop condition followed by start condition is currently being issued instead of the repeated start.

Both [embedded-hal](https://docs.rs/embedded-hal/latest/embedded_hal/i2c/trait.I2c.html#method.write_read) and [embedded-hal-async](https://docs.rs/embedded-hal-async/latest/embedded_hal_async/i2c/trait.I2c.html#method.write_read) specify that `write_read()` uses a repeated start condition.

Some devices like the [veml7700](https://www.vishay.com/docs/84286/veml7700.pdf) require a repeated start. See Fig. 4 - I2C Bus Timing for Receive Word Command Format on page 4.

### PR DESCRIPTION
**Pull request by liebman**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
This is an  implementation of the `I2C::transaction` method for `embedded-hal` and `embedded-hal-async`. Also added native async `read`/`write`/`write_read` methods not requiring `embedded-hal`/`embedded-hal-async`

This fixes #1490

#### Testing
I've tested:
- `esp32` - sync and async
- `esp32s2` - sync and async
- `esp32s3` - sync and async
- `esp32c2` - sync and async
- `esp32c3` - sync and async
- `esp32c6` - sync and async
- `esp32h2` - not tested (I don't have one)

`sync` testing was `i2c_display` and `i2c_bmp180_calibration_data` examples
`async` testing was `embassy_i2c_bmp180_calibration_data` example (new)

### CODE REVIEW

**Comment by bjoernQ** [comment]
Awesome - this works now as expected in regards to #1490 

> Push the "transaction" down into the lower level implementations so that the read/write/write_read (non-embedded-hal trait version) can use the same code rather than a similar but different implementation.

I think that would be the best way to go. We also want to make every driver useable without depending on `embedded-hal` following the _Focus on Drivers_ idea in https://blog.rust-embedded.org/embedded-hal-v1/

I remember we had some issues with the C2 before because the FIFO is only 16x8 bits there (while IIRC all others are 32x8) - we especially had problems with SSD1306 displays - one PR for that was #213 (I think there were follow up PRs)

In general, this will be a great improvement - Thanks for taking care of this!

**Comment by liebman** [comment]
Learned something new for the `esp32`:  The `End` command never gets its `cmd_done` bit set!  The `end_detect` interrupt bit gets set and even after a 1ms delay, the `cmd_done` bit for that is not set. (This is not mentioned in the TRM or the errata).

**Comment by bjoernQ** [comment]
Amazing! Works great for me

I think I remember we usually don't limit the blocking impls to the blocking mode. Did that cause problems here?

**Comment by liebman** [comment]
Yes - It prevented me to from adding `read`/`write`/`write_read` for Async (not using `embedded-hal-async`)

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
