### PR TITLE
Remove unneeded USB generics

### PR DESCRIPTION
**Pull request by MabezDev**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

Closes https://github.com/esp-rs/esp-hal/issues/1465

#### Testing

Running the usb_serial example

### CODE REVIEW

**Comment by MabezDev** [comment]
I will draft this till after the release is out, I imagine we will want an answer to #1468 before merging this to avoid unnecessary churn.

**Review by bjoernQ — APPROVED** [review]
👍 oh yes - keeping the pins in the struct is unnecessary

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by jessebraham — CHANGES_REQUESTED** [review]
Could you add a `CHANGLOG.md` entry for this please?

**Comment by MabezDev** [comment]
#1473 included this change, force merging for the changelog entry

**Pull request merged**
