### PR TITLE
Fix new clippy lints introduced in 1.78 & 1.79

### PR DESCRIPTION
**Pull request by MabezDev**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

### CODE REVIEW

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

**Comment by SergioGasquez** [comment]
HIL builds for S2 and S3 are failing due to changes in the Xtensa Rust toolchain (older versions do not fail) and seems to be something in the `semihosting` crate

**Review by playfulFence — APPROVED** [review]
Thanks a lot for taking care of this that fast!

**Comment by MabezDev** [comment]
Hmm, I can't repro locally :thinking:

**Comment by jessebraham** [comment]
I'm able to reproduce the errors locally, seem to original from the `semihosting@0.1.11` release. Adding the following patch to `hil-test/Cargo.toml`:

```toml
[patch.crates-io]
semihosting = { git = "https://github.com/taiki-e/semihosting", tag = "v0.1.10" }
```

... and then running `cargo update` from within the package's directory results in a successful build on my end.

**Comment by jessebraham** [comment]
FYI I've opened an issue upstream for this: https://github.com/taiki-e/semihosting/issues/11

**Pull request merged**
