### PR TITLE
Update esp-println version in usage section

### PR DESCRIPTION
**Pull request by Szybet**
Makes a mess with features

Do I need to add this to the changelog? I hope not

### CODE REVIEW

**Comment by bugadani** [comment]
I wonder if we need to add `links = "esp-println"` to prevent mixing versions...

**Comment by bjoernQ** [comment]
> I wonder if we need to add `links = "esp-println"` to prevent mixing versions...

we have it now https://github.com/esp-rs/esp-hal/blob/598212a02089ad410a66d7926ccfc803e7abac9d/esp-println/Cargo.toml#L9

**Comment by MabezDev** [comment]
We should probably yank versions before we added the `links` field then?

**Review by bugadani — APPROVED** [review]
Thanks!

**Review by MabezDev — APPROVED** [review]

**Comment by bjoernQ** [comment]
> We should probably yank versions before we added the `links` field then?

Good idea - don't think the old versions are super useful to keep (but wow - a lot to yank)

**Comment by MabezDev** [comment]
> Good idea - don't think the old versions are super useful to keep (but wow - a lot to yank)

Done :)

**Pull request merged**
