### PR TITLE
Fix first UART print

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Review by JurajSadel — APPROVED** [review]
Thanks!

**Review by SergioGasquez — APPROVED** [review]
LGTM!

**Comment by MabezDev** [comment]
Where was this spotted? Is it worth a test case?

**Comment by JurajSadel** [comment]
> Where was this spotted? Is it worth a test case?

I encountered it while running the `hello_world` on C6.

**Review by MabezDev — APPROVED** [review]
Thank you for adding the test case :blush:, LGTM!

**Pull request merged**
