### PR TITLE
Rename PSRAM examples for better discoverability

### PR DESCRIPTION
**Pull request by andresovela**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
I renamed the examples for better discoverability. I was looking for a PSRAM example and I didn't notice that there was one example for the octal I/O PSRAM. I would have noticed had the example been named psram_xxx.rs

#### Testing
I ran the examples with the new names

### CODE REVIEW

**Comment by andresovela** [comment]
Not sure if this change needs a changelog entry

**Review by jessebraham — APPROVED** [review]
I agree this is better now, thanks for this!

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by bjoernQ — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
