### PR TITLE
Adapting maxwen branch to v0.16.1

### LINKED ISSUE #1155: Support for psram on ESP32-PICO-V3-02 (revision v3.0)
Like using in Adafruit ESP32 Feather V2
I managed to make it working and testing so far showed no problems (still needs more testing though)

https://github.com/maxwen/esp-hal/commit/6ba9b84e5cbf55f4ef426de28bfa980599abfcff

Right now this is just a quick and hacky implementation for my personal projects but I would be happy to clean it up
to follow your requirements for contributing. So I was wondering how to get things started.

### PR DESCRIPTION
**Pull request by sebosp**
maxwen@6ba9b84

closes #1155

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
Please provide a clear and concise description of your changes, including the motivation behind these changes. The context is crucial for the reviewers.

#### Testing

Tested building/flashing on M5StickC Plus 2, the examples tested:
- led (blinky)
- esp-wifi with ble, coex, esp-now, embassy.
- i2c ToF hat

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
I unfortunately cannot test this on hardware but changes look good to me

**Comment by bjoernQ** [comment]
Seems this needs code formatting. I think the problem in HIL test is just a hick-up on the GitHub runner
I still can't test it and haven't found anyone else who can but looks good to me

**Comment by sebosp** [comment]
It seems the GitHub runner is happy today and there are no complaints regarding formatting 😄

**Comment by sebosp** [comment]
Nvm now I see the fmt errors popping up, will address them in a few hours

**Review by jessebraham — APPROVED** [review]

**Comment by maxwen** [comment]
Sorry for not coming back to you all for some time - was busy with "life" things ... :(
Thanks for merging my changes. 

I actually did some more changes reformatting that horrible bit masking stuff
which is basically a copy/paste from the C code

So like 
...
    fn EFUSE_SPICONFIG_RET_SPIQ(ret: u32) -> u8 {
        (((ret) >> EFUSE_SPICONFIG_RET_SPIQ_SHIFT) & EFUSE_SPICONFIG_RET_SPIQ_MASK) as u8
    }
...
 a.s.o.

Please checkout 
https://github.com/maxwen/esp-hal/commit/993aa02e3a129cf71238938db02551b6470e61f7 

That is the branch I created wanting to use to create a pull request from before I had to stop.
Its basically the same just a little nicer to look at and to maintain in case other
devices might need the same.

So if you want I can update that branch now to just do the reformatting and create a pull request for
that. But if you say its fine like it is now - Also fine for me :)

Thanks

**Comment by maxwen** [comment]
Added https://github.com/esp-rs/esp-hal/pull/1571 with the cleanup mentioned above

**Pull request merged**
