### PR TITLE
SmartLedsAdapter example requires clocks argument

### PR DESCRIPTION
**Pull request by Dav1dde**
### Submission Checklist 📝
- [X] I have updated existing examples or added new ones (if applicable).
- [X] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [X] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

[SmartLedsAdapter](https://docs.rs/esp-hal-smartled/0.10.0/esp_hal_smartled/struct.SmartLedsAdapter.html) requires 4 arguments, the last one is the clock.

And [Rmt::new](https://docs.esp-rs.org/esp-hal/esp-hal/0.17.0/esp32s3/esp_hal/rmt/struct.Rmt.html#method.new) requires an optional interrupt handler as the last argument.

#### Testing

Tested it with. my esp32s3 :)

### CODE REVIEW

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

**Comment by jessebraham** [comment]
Not sure why this has a `CHANGELOG.md` entry but just a reminder to reviewers, `esp-hal/CHANGELOG.md` is only for changes to the `esp-hal` package.

**Comment by MabezDev** [comment]
I guess we should update https://github.com/esp-rs/esp-hal/blob/00234730680f514f0e0c651bd583ce6218daac1d/.github/workflows/changelog.yml#L6 to ignore projects without a changelog (or add a changelog for these extra projects?)

**Comment by Dav1dde** [comment]
@jessebraham I initially did *not* have one and the CI pushed me to add one (it failed without).

**Pull request merged**
