### PR TITLE
Update esp-synopsys-usb-otg

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
There was a fix for esp-synopsys-usb-otg here: https://github.com/esp-rs-compat/synopsys-usb-otg/pull/1
This includes that fix as a GIT dependency for now. For the next HAL release we'll need to have a new release eso-synopsys-usb-otg, too

#### Testing
Run the existing example and verify it still works as before

### CODE REVIEW

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by MabezDev — APPROVED** [review]
LGTM, but just out of curiosity, is there any reason not to cut a release right now?

**Comment by jessebraham** [comment]
> LGTM, but just out of curiosity, is there any reason not to cut a release right now?

Yeah unless we expect changes to that library in the next week or two, probably makes sense to just publish it now and be done with it.

**Comment by bjoernQ** [comment]
I can do a release maybe early next week just in case someone notices some bad newly introduced behavior (don't expect that). Could probably be a patch release?

**Comment by bjoernQ** [comment]
Closing this ... there is a patch release now. While not really needed will create a PR to use it

**Pull request closed without merging**
