### PR TITLE
Guide: Clarify that Level can be used as an output signal

### PR DESCRIPTION
**Pull request by bugadani**

### CODE REVIEW

**Review by MabezDev — APPROVED** [review]

**Comment by Dominaezzz** [comment]
I could've sworn `Level` only works for Output + Input rather than just Output.

**Comment by bugadani** [comment]
> EDIT: Nvm, I just verified it works.

Wait, what? I just found out that Level doesn't implement Peripheral and I can't pass it to anything 🤣

**Comment by Dominaezzz** [comment]
Ah that's odd, I passed it to I8080 and it compiled fine.

I must admit implementing `Peripheral` for `Level` is a bit strange (though I think I understand why it's needed here).
I'm wondering if drivers should take the `PeripheralOuput`/`PeripheralInput` trait directly rather than going through the `Peripheral` trait.

**Review by bjoernQ — APPROVED** [review]
LGTM

**Pull request merged**
