### PR TITLE
Add reset functionalities

### PR DESCRIPTION
**Pull request by AnthonyGrondin**
This is an early work in progress to add reset functionalities for each chip.  
This is heavily inspired by https://github.com/esp-rs/esp-idf-hal/blob/master/src/reset.rs

It is to be determined if sleep functionalities should also be implemented in this PR.

TODO:
 - [x] software_reset();
 - [x] software_reset_cpu();
 - [ ] rtc_get_wakeup_cause();
   - Create enum like `SocResetReason`, for wakeup cause
   - References:
     - https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv418esp_sleep_source_t
     - https://github.com/espressif/esp-idf/blob/370e2500721513b228b51a72a677be605d276805/components/esp_hw_support/include/esp_sleep.h#L85-L99
 - [ ] Documentation
 - [ ] Examples

Ping:
@jessebraham I'm currently stuck at determining the values for an enum, like `SocResetReason` for the wakeup cause of the chip

### CODE REVIEW

**Comment by jessebraham** [comment]
I had copied from the C-style enums in ESP-IDF, which start at 0 and increment by 1 for each entry. For `SocResetReason` unfortunately there were per-chip definitions, plus some collisions, so not _every_ reason was included.

Looking at the `esp_sleep_source_t` enum though, it seems simple enough; `ESP_SLEEP_WAKEUP_UNDEFINED` should be 0 and `ESP_SLEEP_WAKEUP_BT` should be 12, as far as I can tell.

**Comment by AnthonyGrondin** [comment]
I've checked the return value of `rtc_get_wakeup_cause`, and it returns large numbers like:
  - 61505 : Normal reset after flash
  - 61516 : After calling `software_reset_cpu()`

Any hindsight on what would cause that? I've been testing on `esp32s3`.

**Comment by bjoernQ** [comment]
Seems like `rtc_get_wakeup_cause` is defined as
`WAKEUP_REASON rtc_get_wakeup_cause(void);`

And `WAKEUP_REASON` looks like
```c
typedef enum {
    NO_SLEEP        = 0,
    EXT_EVENT0_TRIG = BIT0,
    EXT_EVENT1_TRIG = BIT1,
    GPIO_TRIG       = BIT2,
    TIMER_EXPIRE    = BIT3,
    SDIO_TRIG       = BIT4,
    MAC_TRIG        = BIT5,
    UART0_TRIG      = BIT6,
    UART1_TRIG      = BIT7,
    TOUCH_TRIG      = BIT8,
    SAR_TRIG        = BIT9,
    BT_TRIG         = BIT10,
    RISCV_TRIG      = BIT11,
    XTAL_DEAD_TRIG  = BIT12,
    RISCV_TRAP_TRIG = BIT13,
    USB_TRIG        = BIT14
} WAKEUP_REASON;
```
So, it seems to be a bitfield

Interesting thing is that esp-idf's `esp_sleep_get_wakeup_cause` doesn't use that ROM function but `rtc_cntl_ll_get_wakeup_cause` (on S3) which just reads `RTC_CNTL_SLP_WAKEUP_CAUSE_REG` - but it seems it does the same thing.

In the end `esp_sleep_get_wakeup_cause` maps the set bits to `esp_sleep_wakeup_cause_t`: 
https://github.com/espressif/esp-idf/blob/afbdb0f3ef195ab51690a64e22bfb8a5cd487914/components/esp_hw_support/sleep_modes.c#L1389-L1444

Same thing is needed for esp-hal

**Comment by AnthonyGrondin** [comment]
@jessebraham or another contributor, do you want to take care of it, so it makes it in the next release?  

I'm pretty busy at the moment, and I won't have time to finish it, in the following weeks.

**Comment by bjoernQ** [comment]
> @jessebraham or another contributor, do you want to take care of it, so it makes it in the next release?
> 
> I'm pretty busy at the moment, and I won't have time to finish it, in the following weeks.

Thanks for letting us know! I don't know when I would get to this so I'd suggest if anyone takes over this please add a note here so we don't end up with duplicate work

**Comment by JurajSadel** [comment]
I can look into this PR

**Comment by JurajSadel** [comment]
https://github.com/esp-rs/esp-hal/pull/452 has been built on top of this PR and has been merged, so I'm closing this one, thanks @AnthonyGrondin for starting this!

**Pull request closed without merging**
