### PR TITLE
Add TimerWakeupSource for the esp32-c6 deepsleep.

### PR DESCRIPTION
**Pull request by t-moe**
This PR adds support for deepsleep-wakeup by timer on the esp32c6

### CODE REVIEW

**Comment by bjoernQ** [comment]
That's a very useful addition. I guess we should first the #1196 in but from a brief look the code looks good to me

**Comment by t-moe** [comment]
No worries, I can rebase afterwards ^^.

**Review by MabezDev — APPROVED** [review]
Works well for me, thanks for this! Very nice to have.

**Review by bjoernQ — APPROVED** [review]
Works fine in my tests, too! Thanks

**Review by jessebraham — APPROVED** [review]
LGTM, thanks for this!

**Pull request merged**
