### PR TITLE
[ESP32-C3] Restore MCUboot build after moving to `esp-riscv-rt`

### PR DESCRIPTION
**Pull request by gustavonihei**
This PR intends to fix the build for ESP32-C3 with `feature = mcu-boot`, which stopped working after #365.

Furthermore, the CI now builds the examples from `esp32c3-hal` with `--features=mcu-boot`.

## NOTE

~~Keeping the PR in draft state since it depends on https://github.com/esp-rs/esp-riscv-rt/pull/4.~~

### CODE REVIEW

**Comment by bjoernQ** [comment]
Maybe I am missing something important here but I think the change in `esp-riscv-rt` isn't necessary.

You can get the `_start` symbol with something like this
```rust
...
    extern "C" {
        fn _start();
    }
    println!("{:x}", _start as u32);
...
```

**Comment by gustavonihei** [comment]
> Maybe I am missing something important here but I think the change in `esp-riscv-rt` isn't necessary.
> 
> You can get the `_start` symbol with something like this
> 
> ```rust
> ...
>     extern "C" {
>         fn _start();
>     }
>     println!("{:x}", _start as u32);
> ...
> ```

I remember trying this back then when implementing MCUboot support in #49 and failing to build it, but now it simply worked. Thanks for the suggestion, @bjoernQ!

**Review by bjoernQ — APPROVED** [review]
I haven't tested it (since testing it is a bit involved) but the code looks fine to me

**Comment by gustavonihei** [comment]
@bjoernQ I've added a couple of commits to the PR to reenable the CI build with `feature=mcu-boot`.

**Review by MabezDev — APPROVED** [review]
LGTM, thanks for fixing this @gustavonihei!

**Comment by bjoernQ** [comment]
I also tried it now following the given instructions and it worked fine 👍

**Pull request merged**
