### PR TITLE
fix: i2c - async write_read in parallel

### PR DESCRIPTION
**Pull request by elpiel**
Attempt at parallelising the `write_read` I2C async fn implementation.

- [ ] There might be a need for a join-style `async fn wait_for_completion` that will wait for both operations to finish, instead of `select`-ing one or the other

### Must

- [ ] The code compiles without `errors` or `warnings`.
- [ ] All examples work.
- [ ] `cargo fmt` was run.
- [ ] Your changes were added to the `CHANGELOG.md` in the proper section.
- [ ] You updated existing examples or added examples (if applicable).
- [ ] Added examples are checked in CI

### Nice to have

- [x] You add a description of your work to this PR.
- [ ] You added proper docs for your newly added features and code.

### CODE REVIEW

**Comment by jessebraham** [comment]
Thanks for the PR, I'll do my best to get to this next week!

**Comment by MabezDev** [comment]
What's the status here? Can we move this along somehow?

**Comment by elpiel** [comment]
I would suggest someone to pick up this branch/issue and continue it.
I have switched to a different platform for the time being and don't think I'm going back to the issue any time soon.

It still needs a few fixes I suppose and to be tested

**Comment by elpiel** [comment]
@jessebraham where/how was this fixed?
Can you provide a link?

**Comment by jessebraham** [comment]
It wasn't fixed yet, you said you were not going to work on it anymore so I closed the PR. I was planning on looking into it this or next week.

**Pull request closed without merging**
