### PR TITLE
ECC peripheral support for ESP32C2, ESP32C6, and ESP32H2

### PR DESCRIPTION
**Pull request by JurajSadel**
## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [x] All examples work.
- [x] `cargo fmt` was run.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [x] You updated existing examples or added examples (if applicable).
- [x] Added examples are checked in CI

### Nice to have

- [ ] You add a description of your work to this PR.
- [x] You added proper docs for your newly added features and code.

Code taken from [714e170](https://github.com/esp-rs/esp-hal/pull/465/commits/714e1704b3958e13a9bb62d31978130b10909cbc)

@jessebraham While you are on vacation I split the ECC driver from the original PR, if you have already started and/or want to work on this, feel free to close this draft, if not I can continue working on this since H2 is missing, and is slightly different.

### CODE REVIEW

**Comment by MabezDev** [comment]
Mostly works for me, but H2 hangs on `Beginning jacobian point verification tests over secp192r1...`.

**Comment by JurajSadel** [comment]
@MabezDev Hmm, for me H2 tests passed. I tried with two H2 boards but can't reproduce it 🤔

**Comment by bjoernQ** [comment]
> @MabezDev Hmm, for me H2 tests passed. I tried with two H2 boards but can't reproduce it 🤔

Also works for me
```
ECC example
Beginning stress tests...
Beginning affine point multiplication tests over secp192r1...ok (it took 344373 cycles in average)
Beginning affine point multiplication tests over secp256r1...ok (it took 580152 cycles in average)
Beginning affine point verification tests over secp192r1...ok (it took 2668 cycles in average)
Beginning affine point verification tests over secp256r1...ok (it took 3115 cycles in average)
Beginning affine point verification + multiplication tests over secp192r1...ok (it took 344450 cycles in average)
Beginning affine point verification + multiplication tests over secp256r1...ok (it took 576296 cycles in average)
Beginning jacobian point multiplication tests over secp192r1...ok (it took 294402 cycles in average)
Beginning jacobian point multiplication tests over secp256r1...ok (it took 512095 cycles in average)
Beginning jacobian point verification tests over secp192r1...ok (it took 3221 cycles in average)
Beginning jacobian point verification tests over secp256r1...ok (it took 3743 cycles in average)
Beginning affine point verification + jacobian point multiplication tests over secp192r1...ok (it took 294246 cycles in average)
Beginning affine point verification + jacobian point multiplication tests over secp256r1...ok (it took 516075 cycles in average)
Mod operation (256) tests successful!
Mod operation (192) tests successful!
Finished stress tests!
````

**Comment by MabezDev** [comment]
Heh, I wasn't running in release mode, so the curve generation took ages to complete. In release mode, it now works :).

**Review by MabezDev — APPROVED** [review]

**Comment by playfulFence** [comment]
Works fine for me as well! Tested on both `revision 0.1` and `revision 0.2` boards

PS: Build the project in the `release` version, otherwise operations take very long time 😅

**Review by jessebraham — APPROVED** [review]
LGTM, thanks for taking care of this

**Pull request merged**
