### PR TITLE
Run HIL tests as part of PR checks

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Now that the tests take 10 minutes less than before, we might want to use them to catch issues earlier.

#### Testing

Hopefully the PR will test itself.

### CODE REVIEW

**Comment by MabezDev** [comment]
Do we want some way of skipping this in the case where HIL becomes flakey? I'm not all that familiar with GH actions, but it would be nice if we could have a `skip-hil-test` for this case.

**Comment by bugadani** [comment]
For now these shouldn't be required and ideally HIL shouldn't be flakey 😅

**Comment by bugadani** [comment]
A `skip-hil-tests` label might be a good idea just to skip testing for e.g. documentation-only changes. Fingers crossed, but it looks like the flakeiness of the tests have been uncovered and taken care of by #1960. I'll continue to watch the workflow just in case.

**Review by jessebraham — APPROVED** [review]
Thanks!

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
