### PR TITLE
Add example rust-analyzer config for when the project repo is opened

### PR DESCRIPTION
**Pull request by MabezDev**
Not just when esp-hal-common is opened.

### CODE REVIEW

**Comment by bjoernQ** [comment]
I think having it as an example - not as settings.json is convenient - but probably for each HAL and not in root ... Just my 0.02$

**Comment by MabezDev** [comment]
> I had originally included this exact configuration, and we just removed this in https://github.com/esp-rs/esp-hal/commit/1d02bf87c389ce33c19133a3f023e843760721ac, why is it being added back in now? I thought the decision was not to include this file?

This is just the example, not the real thing! If someone opens esp-hal from a fresh clone r-a dies, so I thought it might an idea to have this available.

**Comment by MabezDev** [comment]
Before we make a decision on this, I might try https://code.visualstudio.com/docs/editor/multi-root-workspaces to see if I can work around the ra issues properly

**Comment by jessebraham** [comment]
Closing in favour of #129

**Pull request closed without merging**
