### PR TITLE
include bss size when calculating rwtext address

### LINKED ISSUE #144: [ESP32-C3] Direct boot linker bug
I can't seem to pin it to a specific example, as on two different machines I encounter the error on a different example (timer_interrupts & serial_interrupts). To get this output I ran the following:

```
cargo build --features direct-boot --examples --release
```

```
= note: rust-lld: warning: address (0x42000008) of section .text is not a multiple of alignment (256)
          rust-lld: error: section .bss load address range overlaps with .rwtext
          >>> .bss range is [0x42C0, 0x42CF]
          >>> .rwtext range is [0x42C8, 0x498F]
```

@bjoernQ I believe you worked on the DB feature/linker script, any ideas?

### PR DESCRIPTION
**Pull request by MabezDev**
Closes #144

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM!

**Comment by MabezDev** [comment]
Switched to draft based on https://github.com/esp-rs/esp-hal/issues/144#issuecomment-1209598636 will look into this again in the morning.

**Comment by MabezDev** [comment]
Thanks for the pointer @gustavonihei, I've switched to the method used in the MCU boot PR.

**Review by gustavonihei — APPROVED** [review]

**Comment by bjoernQ** [comment]
Looks good and I can flash and run it 👍

**Pull request merged**
