### PR TITLE
Revert changes related to "CryptoRng" trait

### PR DESCRIPTION
**Pull request by playfulFence**
related to #1296 and #1280

We were able to locate the source of problem for those issues, but the fix is not that straight-forward and requires a bit more analysis.

That is why we decided to roll back all the changes related to `CryptoRng` trait and `ensure_randomness()` function

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM

**Review by JurajSadel — APPROVED** [review]
LGTM!

**Comment by jessebraham** [comment]
@MabezDev @playfulFence I guess we decided not to move forward with this in this morning's meeting? Should this be closed, or am I mistaken?

**Comment by playfulFence** [comment]
@jessebraham yep, this may be dropped I guess

**Pull request closed without merging**
