### PR TITLE
Update probe-rs, prebuild xtask for HIL tests

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

This PR updates mentions of probe-rs to the latest `main` ([9bde591](https://github.com/probe-rs/probe-rs/commit/9bde591c62eb0d9601c32c5dd34fd4f6c44fc1f4)). The changes include implementing system reset for Xtensa MCUs, which I hope will help with transient test runner failures.

#### Testing

~YOLO~

https://github.com/esp-rs/esp-hal/actions/runs/10370992061

### CODE REVIEW

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks for updating it and all your work in `probe-rs`!

**Review by jessebraham — APPROVED** [review]
🤞🏻

**Comment by bugadani** [comment]
Thanks for the approvals, unfortunately there's something fishy still 🙃 I'll investigate tomorrow

**Comment by bugadani** [comment]
I'd appreciate a re-review. xtasks should now be pre-built, saving us a bit of time. Unfortunately probe-rs isn't in a workable state for us right now, but I'd like to land this change regardless.

**Review by JurajSadel — APPROVED** [review]
Thanks!

**Review by MabezDev — APPROVED** [review]
Thanks!

**Pull request merged**
