### PR TITLE
Refactor the `clock` module, provide ROM functions via linker scripts

### PR DESCRIPTION
**Pull request by jessebraham**
- Refactors `clock.rs` and `clocks_ll` into a common `clock` module
- Add a `rom-functions` linker script for each device's HAL
- Use the provided ROM functions instead of transmuting memory addresses
- Fix a warning about an unused import

### CODE REVIEW

**Comment by jessebraham** [comment]
This builds just fine locally for me, no idea why the S2 is failing on GHA.

**Review by bjoernQ — APPROVED** [review]
LGTM

**Comment by bjoernQ** [comment]
Code looks fine to me and I even tried to build the ESP32-S2 examples in WSL (to make sure there isn't a case-sensitivity issue with some file) - compiled fine for me

Still, I'm a bit concerned since it would be awful if all future CI builds would fail for S2

**Comment by bjoernQ** [comment]
One thing that is interesting: In the failing build it shows the invocation of the linker and it's missing ` "-nostartfiles" "-Wl,-Tlinkall.x"` which should come from `.cargo/config.toml`

**Comment by bjoernQ** [comment]
Ok I know what is going on!

In https://github.com/esp-rs/esp-hal/blob/7f8a15ccf565a18eec466687de62829b20c6d5bd/.github/workflows/ci.yml#LL117C7-L117C16

The RUSTFLAGS get set which means it won't take the `rustflags` from `.cargo/config.toml` 

Removing that from the build script should make CI happy again

**Review by MabezDev — APPROVED** [review]
LGTM! Much cleaner now :).

**Comment by jessebraham** [comment]
@bjoernQ good eye! Thank you so much that was driving me crazy 😁 That line should have been removed before the CI changes got merged so that was my bad anyway. Oh well, fixed now!

**Pull request merged**
