### PR TITLE
Use vscode multi-root ws for esp-hal

### PR DESCRIPTION
**Pull request by MabezDev**
To use this, `File -> Open workspace from file`

## Whats working
- Go to the definition and other ide features seem to work flawlessly for each chip-specific hal
- esp-hal-common mostly works too, only `target_arch` stuff doesn't work
- Go to interrupt module from the c3 hal correctly takes you to riscv interrupt module

## Not so good
- You have to open it as a workspace, it doesn't just work
- `"rust-analyzer.cargo.buildScripts.enable": false,` in esp-hal-common is ignore, and prints that annoying error about build scripts failing (doesn't affect IDE usablilty)
- Inside esp-hal-common pac always points to esp32 (current behaviour of main) because it can't know what you're looking for. Maybe this isn't the biggest deal because go to works in the individual pacs

### CODE REVIEW

**Comment by MabezDev** [comment]
It can probably be improved, but I didn't want to spend too long if it's a path we don't want to go down.

**Comment by jessebraham** [comment]
Thanks, I didn't even know this was possible! I'll play around with this a bit, will probably experiment and see how well it works and if there is any other configuration worth adding.

**Comment by bjoernQ** [comment]
Interesting - also didn't know this was possible. In the past I just opened each sub-crate separately in VSCode which worked okay for me. Only had to copy the template setting in esp-hal-common. 

Will give this a try as soon as I get to it.

But maybe we shouldn't force users to use this and keep the templates? 

Anyway I guess we need to write something about how to work with the HAL in (at least) VSCode in the README

**Comment by jessebraham** [comment]
This doesn't seem to be working for me. The settings aren't being applied correctly, as each chip-specific HAL is still reporting `can't find test for crate`, which means that `rust-analyzer.checkOnSave.allTargets` is not being applied.

In the [Multi-root Workspace documentation](https://code.visualstudio.com/docs/editor/multi-root-workspaces) it does have this tidbit:

> Settings that affect the entire editor (for example, UI layout) are ignored. For example, two projects cannot both set the zoom level.

So I'm sort of assuming that since rust-analyzer is modifying the editor (via the type hints it displays, etc.) that these settings are not applied, but I'm not certain whether or not this is the actual cause of the problem.

**Comment by jessebraham** [comment]
This isn't working for me so let's just go with the example configuration from #128 for the time being. Thanks for trying this out though, maybe we can revisit it.

**Review by jessebraham — APPROVED** [review]
Wait I lied, I just can't follow instructions 😁  Working now, thanks!

**Pull request merged**
