### PR TITLE
Remove some examples which are adequately covered by documentation

### PR DESCRIPTION
**Pull request by jessebraham**
Some progress towards #2513. If anybody disagrees that the documentation is an adequate replacement for these examples please let me know and I will make the necessary updates.

Will continue looking for more example to remove.

### CODE REVIEW

**Review by bugadani — APPROVED** [review]

**Comment by elrom** [comment]
Just saw this after the examples were removed. I disagree. e.g. googling "enable_pin_with_cal" now results in not a single decent example.

**Comment by brainstorm** [comment]
Also disagree, I guess that those simple examples will not get proper test coverage once they are in the docs vs the actual source tree?

**Comment by bugadani** [comment]
Keep in mind that our goal is not to take away information, but to make it possible for us to maintain example snippets with reasonable effort. Updating 100+ examples multiple times in a development cycle is not reasonable.

**Comment by brainstorm** [comment]
> Keep in mind that our goal is not to take away information, but to make it possible for us to maintain example snippets with reasonable effort. Updating 100+ examples multiple times in a development cycle is not reasonable.
> 
> Feel free to list any _specifics_ that you are no longer able to find.

Fair point, I didn't consider that angle... Mine was just a general observation from experience: I just find well maintained examples invaluable for quick iteration and extremely frustrating when I have to delve into docs (which invariably have higher bitrot rate) only to realise that API has drifted and need to tweak accordingly, spending time where I shouldn't when resolving a task.

**Comment by jessebraham** [comment]
> Also disagree, I guess that those simple examples will not get proper test coverage once they are in the docs vs the actual source tree?

Examples are not tests. We have hardware-in-loop testing, we have doctests that we build in CI. What specifically do you feel is lost by the removal of these specific examples? The sheer number of examples are a huge burden to the maintainers as it stands.

**Comment by brainstorm** [comment]
Again, no specifics here, just principles: All I'm saying is that as long as the doc examples are copy-pastable and work "out of the box" right away, this approach is fine. Otherwise you'd be trading UX for DX.

**Pull request merged**
