### PR TITLE
PeripheralRef init: uart

### PR DESCRIPTION
**Pull request by MabezDev**
* Add the Peripheral trait & PeripheralRef struct definitions
* Implements Peripheral for each chip UART peripherals (generated a new token which replaces the pac version)
* Renames Serial to Uart to be more in line with trm
* Refactor Uart to use the Peripheral trait constructor
* Refactor examples to use the new Uart driver & Peripherals struct 

This PR allows us to either pass in a mutable reference to a peripheral, which is automatically freed when the driver is dropped, or by value, see the following code snippet:

```rust
let mut uart0 = Uart::new(&mut uart);
writeln!(uart0, "Test 1").unwrap();
drop(uart0); // this ends the mutable borrow of uart, its now available in the peripheral struct again
let mut uart0 = Uart::new(uart); // construct via move this time
writeln!(uart0, "Test 2").unwrap();
```

### CODE REVIEW

**Comment by MabezDev** [comment]
Not quite ready for merge, but in a decent enough spot for some review :).

I've tried to keep the commits clean-ish, and will probably clean them up a little more too. I intend to keep them as a reference for anyone wanting to implement this new idiom for other drivers.

I'll rebase on next, once next has been rebased onto a more recent main commit.

**Comment by bjoernQ** [comment]
Looks amazing - great works

There are quite a lot of changes and I'm wondering if it's really feasible to keep that `next` branch for weeks or maybe months given we won't freeze `main`.
At least the change from `pac` to `peripherals` might be something that would make all our lives easier if we would merge that to `main`?

Also, if I'm not totally off, with this approach we would in theory be able to do things step-by-step? The big disadvantage of that would be that we will annoy users very frequently vs. one big bang when everything is done. Or wait - once that pac vs peripherals thing would be in, it won't change things on the call-site when we migrate a driver?

**Comment by bjoernQ** [comment]
> At least the change from pac to peripherals might be something that would make all our lives easier if we would merge that to main?

Which would mean that crates that need to access registers directly like `esp-wifi` need to depend on the PACs directly - shouldn't be a big deal - we could even prepare for that if we don't merge anything to `main`

**Comment by MabezDev** [comment]
> Looks amazing - great works
> 
> There are quite a lot of changes and I'm wondering if it's really feasible to keep that `next` branch for weeks or maybe months given we won't freeze `main`. At least the change from `pac` to `peripherals` might be something that would make all our lives easier if we would merge that to `main`?
> 
> Also, if I'm not totally off, with this approach we would in theory be able to do things step-by-step? The big disadvantage of that would be that we will annoy users very frequently vs. one big bang when everything is done. Or wait - once that pac vs peripherals thing would be in, it won't change things on the call-site when we migrate a driver?

I would tend to agree, I think maybe we should merge this into main instead. The only downside is that probably don't want to push a release until all drivers are using the new way. I don't think this is too big of a deal because firstly, I don't think transforming all the drivers will take that long (Except gpio maybe :D) - especially if we split the work and maybe do a hackathon day in Brno. Secondly, if we really need to put out a patch release, we can just branch from the last release and apply the fix there and release. Thoughts, @jessebraham?

> Which would mean that crates that need to access registers directly like esp-wifi need to depend on the PACs directly - shouldn't be a big deal - we could even prepare for that if we don't merge anything to main

Yes, crates like esp-wifi, esp-hal-common should depend on the pac's internally as an implementation detail and not expose them publically.

**Comment by bjoernQ** [comment]
And maybe we could split up the GPIO rewrite and the PeripheralRef pattern for GPIO?

Also, I might have an idea for a different take on GPIO refactoring which might be less work - but really need to test it first - might not work at all

**Comment by jessebraham** [comment]
I'm gonna take the weekend to think about this, I'll update you both when I've had some time to consider our options.

**Comment by jessebraham** [comment]
We discussed yesterday how to move forward with this, and have decided on the following:

- Evaluate the `main` branch in its current state, resolve any identified issues
- Triage issues and attempt to clean up and low-hanging fruit
- Publish new releases of each HAL
- Merge this PR into `main`

**Comment by MabezDev** [comment]
From the [list of open bugs](https://github.com/esp-rs/esp-hal/issues?q=is%3Aissue+is%3Aopen+label%3Abug) From my perspective, I suggest we fix #229 and #268 then cut a release. I think the other bugs will probably require a fair bit of investigation before we get to fix them.

**Comment by jessebraham** [comment]
New releases have been published!

**Review by jessebraham — APPROVED** [review]
LGTM, all serial-related examples appear to be working as expected for each chip. Thanks a bunch for all your work on this!

**Review by bjoernQ — APPROVED** [review]
LGTM

Really like the renaming of `Serial`

Just one thing: Would you mind to run `fmt` on all the code (also unchanged code) - we change a lot here already so it shouldn't hurt?

**Pull request merged**
