### PR TITLE
Camel case structs

### PR DESCRIPTION
**Pull request by MabezDev**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description

Builds on top of #1469 

Following on from #1468, this renames all offending drivers. I also took the liberty of nuking some unused GPIO code.

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
LGTM - nice improvement

**Review by SergioGasquez — APPROVED** [review]
LGTM!

**Review by JurajSadel — APPROVED** [review]
LGTM, thanks!

**Review by jessebraham — APPROVED** [review]
Thanks!

**Pull request merged**
