### PR TITLE
Cleanup ESP32-PICO-V3-02 psram efuse bit masking functions

### PR DESCRIPTION
**Pull request by maxwen**
Those functions where just copy paste from the C macros

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/API-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
No functional changes. Just cleanup to look nice and better understandable.

#### Testing
Describe how you tested your changes.

### CODE REVIEW

**Comment by bjoernQ** [comment]
Thanks. I don't think this should be mentioned in the CHANGELOG since it doesn't change anything from a user's perspective - and needs a re-format of the code

**Comment by maxwen** [comment]
Regarding code re-format 
Can you please point me to what needs to be done for this

**Comment by MabezDev** [comment]
> Ok will remove from changelog. Regarding code re-format Can you please point me to what needs to be done for this

`cargo xtask fmt-packages` in the root of esp-hal.

**Review by JurajSadel — COMMENTED** [review]
Sorry for nitpick but there is a warning https://github.com/esp-rs/esp-hal/actions/runs/9189379776/job/25271316858#step:8:443. Could you please have a look?
Otherwise, changes LGTM, thanks!

**Comment by maxwen** [comment]
Done

**Review by bjoernQ — APPROVED** [review]
LGTM

**Review by MabezDev — APPROVED** [review]
Thanks!

**Pull request merged**
